/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;
import studio.livepeer.livepeer.models.errors.SDKError;
import studio.livepeer.livepeer.utils.LazySingletonValue;
import studio.livepeer.livepeer.utils.Utils;


public class CreateClipRequestBuilder {

    private studio.livepeer.livepeer.models.components.ClipPayload request;
    private final SDKMethodInterfaces.MethodCallCreateClip sdk;

    public CreateClipRequestBuilder(SDKMethodInterfaces.MethodCallCreateClip sdk) {
        this.sdk = sdk;
    }

    public CreateClipRequestBuilder request(studio.livepeer.livepeer.models.components.ClipPayload request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateClipResponse call() throws Exception {

        return sdk.createClip(
            request);
    }
}
