/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations;

import static studio.livepeer.livepeer.operations.Operations.RequestOperation;

import java.lang.Exception;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.models.components.MultistreamTargetInput;
import studio.livepeer.livepeer.operations.CreateMultistreamTarget;
import studio.livepeer.livepeer.utils.Headers;
import studio.livepeer.livepeer.utils.Utils;

public class CreateMultistreamTargetRequestBuilder {

    private MultistreamTargetInput request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public CreateMultistreamTargetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateMultistreamTargetRequestBuilder request(MultistreamTargetInput request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateMultistreamTargetResponse call() throws Exception {
        
        RequestOperation<MultistreamTargetInput, CreateMultistreamTargetResponse> operation
              = new CreateMultistreamTarget.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
