/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations;

import static studio.livepeer.livepeer.operations.Operations.RequestOperation;

import java.lang.String;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.operations.DeleteRoomUser;
import studio.livepeer.livepeer.utils.Headers;
import studio.livepeer.livepeer.utils.Utils;

public class DeleteRoomUserRequestBuilder {

    private String id;
    private String userId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public DeleteRoomUserRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteRoomUserRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public DeleteRoomUserRequestBuilder userId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }


    private DeleteRoomUserRequest buildRequest() {

        DeleteRoomUserRequest request = new DeleteRoomUserRequest(id,
            userId);

        return request;
    }

    public DeleteRoomUserResponse call() {
        
        RequestOperation<DeleteRoomUserRequest, DeleteRoomUserResponse> operation
              = new DeleteRoomUser.Sync(sdkConfiguration, _headers);
        DeleteRoomUserRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
