/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.operations;

import java.lang.String;
import studio.livepeer.livepeer.utils.Utils;

public class DeleteRoomRequestBuilder {

    private String id;
    private final SDKMethodInterfaces.MethodCallDeleteRoom sdk;

    public DeleteRoomRequestBuilder(SDKMethodInterfaces.MethodCallDeleteRoom sdk) {
        this.sdk = sdk;
    }

    public DeleteRoomRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public DeleteRoomResponse call() throws Exception {

        return sdk.delete(
            id);
    }
}
