/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import studio.livepeer.livepeer.utils.Utils;
/**
 * GetPublicViewershipMetricsData - A simplified metric object about aggregate viewership of an
 * asset. Either playbackId or dStorageUrl will be set.
 * 
 */

public class GetPublicViewershipMetricsData {

    /**
     * The playback ID associated with the metric.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("playbackId")
    private Optional<? extends String> playbackId;

    /**
     * The URL of the distributed storage used for the asset
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dStorageUrl")
    private Optional<? extends String> dStorageUrl;

    /**
     * The number of views for the asset.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("viewCount")
    private Optional<? extends Long> viewCount;

    /**
     * The total playtime in minutes for the asset.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("playtimeMins")
    private Optional<? extends Double> playtimeMins;

    @JsonCreator
    public GetPublicViewershipMetricsData(
            @JsonProperty("playbackId") Optional<? extends String> playbackId,
            @JsonProperty("dStorageUrl") Optional<? extends String> dStorageUrl,
            @JsonProperty("viewCount") Optional<? extends Long> viewCount,
            @JsonProperty("playtimeMins") Optional<? extends Double> playtimeMins) {
        Utils.checkNotNull(playbackId, "playbackId");
        Utils.checkNotNull(dStorageUrl, "dStorageUrl");
        Utils.checkNotNull(viewCount, "viewCount");
        Utils.checkNotNull(playtimeMins, "playtimeMins");
        this.playbackId = playbackId;
        this.dStorageUrl = dStorageUrl;
        this.viewCount = viewCount;
        this.playtimeMins = playtimeMins;
    }
    
    public GetPublicViewershipMetricsData() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * The playback ID associated with the metric.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> playbackId() {
        return (Optional<String>) playbackId;
    }

    /**
     * The URL of the distributed storage used for the asset
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> dStorageUrl() {
        return (Optional<String>) dStorageUrl;
    }

    /**
     * The number of views for the asset.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Long> viewCount() {
        return (Optional<Long>) viewCount;
    }

    /**
     * The total playtime in minutes for the asset.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Double> playtimeMins() {
        return (Optional<Double>) playtimeMins;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The playback ID associated with the metric.
     */
    public GetPublicViewershipMetricsData withPlaybackId(String playbackId) {
        Utils.checkNotNull(playbackId, "playbackId");
        this.playbackId = Optional.ofNullable(playbackId);
        return this;
    }

    /**
     * The playback ID associated with the metric.
     */
    public GetPublicViewershipMetricsData withPlaybackId(Optional<? extends String> playbackId) {
        Utils.checkNotNull(playbackId, "playbackId");
        this.playbackId = playbackId;
        return this;
    }

    /**
     * The URL of the distributed storage used for the asset
     */
    public GetPublicViewershipMetricsData withDStorageUrl(String dStorageUrl) {
        Utils.checkNotNull(dStorageUrl, "dStorageUrl");
        this.dStorageUrl = Optional.ofNullable(dStorageUrl);
        return this;
    }

    /**
     * The URL of the distributed storage used for the asset
     */
    public GetPublicViewershipMetricsData withDStorageUrl(Optional<? extends String> dStorageUrl) {
        Utils.checkNotNull(dStorageUrl, "dStorageUrl");
        this.dStorageUrl = dStorageUrl;
        return this;
    }

    /**
     * The number of views for the asset.
     */
    public GetPublicViewershipMetricsData withViewCount(long viewCount) {
        Utils.checkNotNull(viewCount, "viewCount");
        this.viewCount = Optional.ofNullable(viewCount);
        return this;
    }

    /**
     * The number of views for the asset.
     */
    public GetPublicViewershipMetricsData withViewCount(Optional<? extends Long> viewCount) {
        Utils.checkNotNull(viewCount, "viewCount");
        this.viewCount = viewCount;
        return this;
    }

    /**
     * The total playtime in minutes for the asset.
     */
    public GetPublicViewershipMetricsData withPlaytimeMins(double playtimeMins) {
        Utils.checkNotNull(playtimeMins, "playtimeMins");
        this.playtimeMins = Optional.ofNullable(playtimeMins);
        return this;
    }

    /**
     * The total playtime in minutes for the asset.
     */
    public GetPublicViewershipMetricsData withPlaytimeMins(Optional<? extends Double> playtimeMins) {
        Utils.checkNotNull(playtimeMins, "playtimeMins");
        this.playtimeMins = playtimeMins;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetPublicViewershipMetricsData other = (GetPublicViewershipMetricsData) o;
        return 
            java.util.Objects.deepEquals(this.playbackId, other.playbackId) &&
            java.util.Objects.deepEquals(this.dStorageUrl, other.dStorageUrl) &&
            java.util.Objects.deepEquals(this.viewCount, other.viewCount) &&
            java.util.Objects.deepEquals(this.playtimeMins, other.playtimeMins);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            playbackId,
            dStorageUrl,
            viewCount,
            playtimeMins);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetPublicViewershipMetricsData.class,
                "playbackId", playbackId,
                "dStorageUrl", dStorageUrl,
                "viewCount", viewCount,
                "playtimeMins", playtimeMins);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> playbackId = Optional.empty();
 
        private Optional<? extends String> dStorageUrl = Optional.empty();
 
        private Optional<? extends Long> viewCount = Optional.empty();
 
        private Optional<? extends Double> playtimeMins = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The playback ID associated with the metric.
         */
        public Builder playbackId(String playbackId) {
            Utils.checkNotNull(playbackId, "playbackId");
            this.playbackId = Optional.ofNullable(playbackId);
            return this;
        }

        /**
         * The playback ID associated with the metric.
         */
        public Builder playbackId(Optional<? extends String> playbackId) {
            Utils.checkNotNull(playbackId, "playbackId");
            this.playbackId = playbackId;
            return this;
        }

        /**
         * The URL of the distributed storage used for the asset
         */
        public Builder dStorageUrl(String dStorageUrl) {
            Utils.checkNotNull(dStorageUrl, "dStorageUrl");
            this.dStorageUrl = Optional.ofNullable(dStorageUrl);
            return this;
        }

        /**
         * The URL of the distributed storage used for the asset
         */
        public Builder dStorageUrl(Optional<? extends String> dStorageUrl) {
            Utils.checkNotNull(dStorageUrl, "dStorageUrl");
            this.dStorageUrl = dStorageUrl;
            return this;
        }

        /**
         * The number of views for the asset.
         */
        public Builder viewCount(long viewCount) {
            Utils.checkNotNull(viewCount, "viewCount");
            this.viewCount = Optional.ofNullable(viewCount);
            return this;
        }

        /**
         * The number of views for the asset.
         */
        public Builder viewCount(Optional<? extends Long> viewCount) {
            Utils.checkNotNull(viewCount, "viewCount");
            this.viewCount = viewCount;
            return this;
        }

        /**
         * The total playtime in minutes for the asset.
         */
        public Builder playtimeMins(double playtimeMins) {
            Utils.checkNotNull(playtimeMins, "playtimeMins");
            this.playtimeMins = Optional.ofNullable(playtimeMins);
            return this;
        }

        /**
         * The total playtime in minutes for the asset.
         */
        public Builder playtimeMins(Optional<? extends Double> playtimeMins) {
            Utils.checkNotNull(playtimeMins, "playtimeMins");
            this.playtimeMins = playtimeMins;
            return this;
        }
        
        public GetPublicViewershipMetricsData build() {
            return new GetPublicViewershipMetricsData(
                playbackId,
                dStorageUrl,
                viewCount,
                playtimeMins);
        }
    }
}

