/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations;

import static studio.livepeer.livepeer.operations.Operations.RequestlessOperation;

import java.lang.Exception;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.operations.GetSessions;
import studio.livepeer.livepeer.utils.Headers;

public class GetSessionsRequestBuilder {

    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetSessionsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetSessionsResponse call() throws Exception {
        
        RequestlessOperation<GetSessionsResponse> operation
            = new GetSessions.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest());
    }
}
