/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.operations;

import java.lang.String;
import studio.livepeer.livepeer.utils.Utils;

public class GetSessionClipsRequestBuilder {

    private String id;
    private final SDKMethodInterfaces.MethodCallGetSessionClips sdk;

    public GetSessionClipsRequestBuilder(SDKMethodInterfaces.MethodCallGetSessionClips sdk) {
        this.sdk = sdk;
    }

    public GetSessionClipsRequestBuilder id(java.lang.String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public GetSessionClipsResponse call() throws Exception {

        return sdk.getClips(
            id);
    }
}
