/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.operations;

import java.lang.String;
import java.util.Optional;
import studio.livepeer.livepeer.utils.Utils;

public class GetStreamsRequestBuilder {

    private Optional<String> streamsonly = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetStreams sdk;

    public GetStreamsRequestBuilder(SDKMethodInterfaces.MethodCallGetStreams sdk) {
        this.sdk = sdk;
    }
                
    public GetStreamsRequestBuilder streamsonly(String streamsonly) {
        Utils.checkNotNull(streamsonly, "streamsonly");
        this.streamsonly = Optional.of(streamsonly);
        return this;
    }

    public GetStreamsRequestBuilder streamsonly(Optional<String> streamsonly) {
        Utils.checkNotNull(streamsonly, "streamsonly");
        this.streamsonly = streamsonly;
        return this;
    }

    public GetStreamsResponse call() throws Exception {

        return sdk.getAll(
            streamsonly);
    }
}
