/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations;

import static studio.livepeer.livepeer.operations.Operations.RequestlessOperation;

import java.lang.Exception;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.operations.GetTasks;
import studio.livepeer.livepeer.utils.Headers;

public class GetTasksRequestBuilder {

    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetTasksRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetTasksResponse call() throws Exception {
        
        RequestlessOperation<GetTasksResponse> operation
            = new GetTasks.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest());
    }
}
