/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;
import studio.livepeer.livepeer.models.errors.SDKError;
import studio.livepeer.livepeer.utils.LazySingletonValue;
import studio.livepeer.livepeer.utils.Utils;


public class GetTaskRequestBuilder {

    private String taskId;
    private final SDKMethodInterfaces.MethodCallGetTask sdk;

    public GetTaskRequestBuilder(SDKMethodInterfaces.MethodCallGetTask sdk) {
        this.sdk = sdk;
    }

    public GetTaskRequestBuilder taskId(String taskId) {
        Utils.checkNotNull(taskId, "taskId");
        this.taskId = taskId;
        return this;
    }

    public GetTaskResponse call() throws Exception {

        return sdk.get(
            taskId);
    }
}
