/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations;

import static studio.livepeer.livepeer.operations.Operations.RequestOperation;

import java.lang.Exception;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.operations.GetViewershipMetricsOperation;
import studio.livepeer.livepeer.utils.Utils;

public class GetViewershipMetricsRequestBuilder {

    private GetViewershipMetricsRequest request;
    private final SDKConfiguration sdkConfiguration;

    public GetViewershipMetricsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetViewershipMetricsRequestBuilder request(GetViewershipMetricsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetViewershipMetricsResponse call() throws Exception {
        
        RequestOperation<GetViewershipMetricsRequest, GetViewershipMetricsResponse> operation
              = new GetViewershipMetricsOperation( sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
