/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations;

import static studio.livepeer.livepeer.operations.Operations.RequestOperation;

import java.lang.Exception;
import java.lang.String;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.operations.GetWebhookLogOperation;
import studio.livepeer.livepeer.utils.Utils;

public class GetWebhookLogRequestBuilder {

    private String id;
    private String logId;
    private final SDKConfiguration sdkConfiguration;

    public GetWebhookLogRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetWebhookLogRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public GetWebhookLogRequestBuilder logId(String logId) {
        Utils.checkNotNull(logId, "logId");
        this.logId = logId;
        return this;
    }


    private GetWebhookLogRequest buildRequest() {

        GetWebhookLogRequest request = new GetWebhookLogRequest(id,
            logId);

        return request;
    }

    public GetWebhookLogResponse call() throws Exception {
        
        RequestOperation<GetWebhookLogRequest, GetWebhookLogResponse> operation
              = new GetWebhookLogOperation( sdkConfiguration);
        GetWebhookLogRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
