/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations;

import static studio.livepeer.livepeer.operations.Operations.RequestOperation;

import java.lang.Exception;
import java.lang.String;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.operations.ResendWebhook;
import studio.livepeer.livepeer.utils.Headers;
import studio.livepeer.livepeer.utils.Utils;

public class ResendWebhookRequestBuilder {

    private String id;
    private String logId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ResendWebhookRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ResendWebhookRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public ResendWebhookRequestBuilder logId(String logId) {
        Utils.checkNotNull(logId, "logId");
        this.logId = logId;
        return this;
    }


    private ResendWebhookRequest buildRequest() {

        ResendWebhookRequest request = new ResendWebhookRequest(id,
            logId);

        return request;
    }

    public ResendWebhookResponse call() throws Exception {
        
        RequestOperation<ResendWebhookRequest, ResendWebhookResponse> operation
              = new ResendWebhook.Sync(sdkConfiguration, _headers);
        ResendWebhookRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
