/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;
import studio.livepeer.livepeer.models.errors.SDKError;
import studio.livepeer.livepeer.utils.LazySingletonValue;
import studio.livepeer.livepeer.utils.Utils;


public class StartRoomEgressRequestBuilder {

    private String id;
    private studio.livepeer.livepeer.models.components.RoomEgressPayload roomEgressPayload;
    private final SDKMethodInterfaces.MethodCallStartRoomEgress sdk;

    public StartRoomEgressRequestBuilder(SDKMethodInterfaces.MethodCallStartRoomEgress sdk) {
        this.sdk = sdk;
    }

    public StartRoomEgressRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public StartRoomEgressRequestBuilder roomEgressPayload(studio.livepeer.livepeer.models.components.RoomEgressPayload roomEgressPayload) {
        Utils.checkNotNull(roomEgressPayload, "roomEgressPayload");
        this.roomEgressPayload = roomEgressPayload;
        return this;
    }

    public StartRoomEgressResponse call() throws Exception {

        return sdk.startEgress(
            id,
            roomEgressPayload);
    }
}
