/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;
import studio.livepeer.livepeer.models.errors.SDKError;
import studio.livepeer.livepeer.utils.LazySingletonValue;
import studio.livepeer.livepeer.utils.Utils;


public class UpdateWebhookRequestBuilder {

    private String id;
    private studio.livepeer.livepeer.models.components.WebhookInput webhook;
    private final SDKMethodInterfaces.MethodCallUpdateWebhook sdk;

    public UpdateWebhookRequestBuilder(SDKMethodInterfaces.MethodCallUpdateWebhook sdk) {
        this.sdk = sdk;
    }

    public UpdateWebhookRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public UpdateWebhookRequestBuilder webhook(studio.livepeer.livepeer.models.components.WebhookInput webhook) {
        Utils.checkNotNull(webhook, "webhook");
        this.webhook = webhook;
        return this;
    }

    public UpdateWebhookResponse call() throws Exception {

        return sdk.update(
            id,
            webhook);
    }
}
