/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations.async;

import static studio.livepeer.livepeer.operations.Operations.AsyncRequestOperation;

import java.lang.String;
import java.util.concurrent.CompletableFuture;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.models.operations.DeleteRoomRequest;
import studio.livepeer.livepeer.operations.DeleteRoom;
import studio.livepeer.livepeer.utils.Headers;
import studio.livepeer.livepeer.utils.Utils;

public class DeleteRoomRequestBuilder {

    private String id;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public DeleteRoomRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteRoomRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }


    private DeleteRoomRequest buildRequest() {

        DeleteRoomRequest request = new DeleteRoomRequest(id);

        return request;
    }

    public CompletableFuture<DeleteRoomResponse> call() {
        
        AsyncRequestOperation<DeleteRoomRequest, DeleteRoomResponse> operation
              = new DeleteRoom.Async(sdkConfiguration, _headers);
        DeleteRoomRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
