/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations.async;

import static studio.livepeer.livepeer.operations.Operations.AsyncRequestOperation;

import java.lang.Exception;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.models.operations.GetWebhookLogsRequest;
import studio.livepeer.livepeer.operations.GetWebhookLogs;
import studio.livepeer.livepeer.utils.Headers;
import studio.livepeer.livepeer.utils.Utils;

public class GetWebhookLogsRequestBuilder {

    private String id;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetWebhookLogsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetWebhookLogsRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }


    private GetWebhookLogsRequest buildRequest() {

        GetWebhookLogsRequest request = new GetWebhookLogsRequest(id);

        return request;
    }

    public CompletableFuture<GetWebhookLogsResponse> call() throws Exception {
        
        AsyncRequestOperation<GetWebhookLogsRequest, GetWebhookLogsResponse> operation
              = new GetWebhookLogs.Async(sdkConfiguration, _headers);
        GetWebhookLogsRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
