/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations.async;

import static studio.livepeer.livepeer.operations.Operations.AsyncRequestOperation;

import java.lang.Exception;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.models.operations.TerminateStreamRequest;
import studio.livepeer.livepeer.operations.TerminateStream;
import studio.livepeer.livepeer.utils.Headers;
import studio.livepeer.livepeer.utils.Utils;

public class TerminateStreamRequestBuilder {

    private String id;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public TerminateStreamRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public TerminateStreamRequestBuilder id(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }


    private TerminateStreamRequest buildRequest() {

        TerminateStreamRequest request = new TerminateStreamRequest(id);

        return request;
    }

    public CompletableFuture<TerminateStreamResponse> call() throws Exception {
        
        AsyncRequestOperation<TerminateStreamRequest, TerminateStreamResponse> operation
              = new TerminateStream.Async(sdkConfiguration, _headers);
        TerminateStreamRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
