/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.operations.async;

import static studio.livepeer.livepeer.operations.Operations.AsyncRequestOperation;

import java.lang.Exception;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import studio.livepeer.livepeer.SDKConfiguration;
import studio.livepeer.livepeer.models.operations.UpdateSigningKeyRequest;
import studio.livepeer.livepeer.models.operations.UpdateSigningKeyRequestBody;
import studio.livepeer.livepeer.operations.UpdateSigningKey;
import studio.livepeer.livepeer.utils.Headers;
import studio.livepeer.livepeer.utils.Utils;

public class UpdateSigningKeyRequestBuilder {

    private String keyId;
    private UpdateSigningKeyRequestBody requestBody;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public UpdateSigningKeyRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public UpdateSigningKeyRequestBuilder keyId(String keyId) {
        Utils.checkNotNull(keyId, "keyId");
        this.keyId = keyId;
        return this;
    }

    public UpdateSigningKeyRequestBuilder requestBody(UpdateSigningKeyRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }


    private UpdateSigningKeyRequest buildRequest() {

        UpdateSigningKeyRequest request = new UpdateSigningKeyRequest(keyId,
            requestBody);

        return request;
    }

    public CompletableFuture<UpdateSigningKeyResponse> call() throws Exception {
        
        AsyncRequestOperation<UpdateSigningKeyRequest, UpdateSigningKeyResponse> operation
              = new UpdateSigningKey.Async(sdkConfiguration, _headers);
        UpdateSigningKeyRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
