/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer;

import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import java.util.concurrent.TimeUnit;

import java.lang.IllegalStateException;
import java.lang.String;
import java.lang.System;
import java.util.Optional;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.function.Consumer;
import studio.livepeer.livepeer.utils.BackoffStrategy;
import studio.livepeer.livepeer.utils.HTTPClient;
import studio.livepeer.livepeer.utils.RetryConfig;
import studio.livepeer.livepeer.utils.SpeakeasyHTTPClient;


/**
 * Spring Boot Auto Configuration for openapi SDK
 * This configuration class automatically configures the openapi SDK
 * when Spring Boot detects it on the classpath.
 */
@AutoConfiguration
@ConditionalOnClass(Livepeer.class)
@EnableConfigurationProperties(OpenapiAutoConfigProperties.class)
public class OpenapiAutoConfig {

    /**
     * Constructor.
     */
    public OpenapiAutoConfig() {
    }

    /**
     * Creates a RetryConfig bean from properties if retry is enabled.
     * 
     * @param properties the configuration properties
     * @return A configured RetryConfig instance
     */
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(prefix = "openapi.retry-config", name = "strategy")
    public RetryConfig retryConfig(OpenapiAutoConfigProperties properties) {
        OpenapiAutoConfigProperties.RetryConfig retryProps = properties.getRetryConfig();
        
        if (RetryConfig.Strategy.BACKOFF.equals(retryProps.getStrategy())) {
            OpenapiAutoConfigProperties.RetryConfig.Backoff backoff = retryProps.getBackoff();
            return RetryConfig.builder()
                .backoff(
                    BackoffStrategy.builder()
                        .initialInterval(backoff.getInitialInterval().toMillis(), TimeUnit.MILLISECONDS)
                        .maxInterval(backoff.getMaxInterval().toMillis(), TimeUnit.MILLISECONDS)
                        .maxElapsedTime(backoff.getMaxElapsedTime().toMillis(), TimeUnit.MILLISECONDS)
                        .baseFactor(backoff.getBaseFactor())
                        .jitterFactor(backoff.getJitterFactor())
                        .retryConnectError(backoff.isRetryConnectError())
                        .retryReadTimeoutError(backoff.isRetryReadTimeoutError())
                        .build()
                )
                .build();
        }
        
        // Default retry config for other strategies
        return RetryConfig.builder().build();
    }
    /**
     * Creates a {@code Consumer<String>} bean for HTTP debug logging if none exists.
     * This logger is used by the SpeakeasyHTTPClient for debug output when debug logging is enabled.
     * By default, it logs to {@code System.out}, but can be customized by providing your own {@code Consumer<String>} bean.
     *
     * @return A {@code Consumer<String>} that logs messages to {@code System.out}
     */
    @Bean
    @ConditionalOnMissingBean
    public Consumer<String> httpLogger() {
        return System.out::println;
    }
    /**
     * Creates an HTTPClient bean if none exists.
     *
     * @param properties the configuration properties
     * @param httpLogger the logger for HTTP debug output
     * @return A configured HTTPClient instance
     */
    @Bean
    @ConditionalOnMissingBean
    public HTTPClient httpClient(OpenapiAutoConfigProperties properties, Consumer<String> httpLogger) {
        OpenapiAutoConfigProperties.HttpClient httpClientProps = properties.getHttpClient();

        // Configure the static logger
        SpeakeasyHTTPClient.setLogger(httpLogger);

        if (httpClientProps != null) {
            // Configure debug logging
            SpeakeasyHTTPClient.setDebugLogging(httpClientProps.isEnableDebugLogging());

            // Configure redacted headers
            if (httpClientProps.getRedactedHeaders() != null && !httpClientProps.getRedactedHeaders().isEmpty()) {
                SpeakeasyHTTPClient.setRedactedHeaders(httpClientProps.getRedactedHeaders());
            }
        }

        return new SpeakeasyHTTPClient();
    }
    /**
     * Creates a SecuritySource bean if none exists and security properties are configured.
     *
     * @param properties the configuration properties
     * @return A configured SecuritySource instance
     */
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnPropertyPrefix(prefix = "openapi.security")
    public SecuritySource securitySource(OpenapiAutoConfigProperties properties) {OpenapiAutoConfigProperties.Security securityProps = properties.getSecurity();
        studio.livepeer.livepeer.models.components.Security.Builder securityBuilder = studio.livepeer.livepeer.models.components.Security.builder();
        boolean hasAnySecurityConfiguration = false;
        // Build apiKey security from direct properties (primitive value)
        if (securityProps.getApiKey() != null) {
            securityBuilder.apiKey(securityProps.getApiKey());
            hasAnySecurityConfiguration = true;
        }
        
        if (!hasAnySecurityConfiguration) {
            throw new IllegalStateException("Security configuration is present but no security options are configured. " +
                "Please configure at least one security option in your application properties.");
        }
        
        return SecuritySource.of(securityBuilder.build());
    }

    /**
     * Creates the SDKConfiguration bean as the single source of truth for all SDK configuration.
     *
     * @param properties the configuration properties
     * @param httpClient the HTTP client bean
     * @param hooks the hooks bean
     * @param asyncHooks the async hooks bean
     * @param securitySource the security source bean (optional)
     * @param retryConfig the retry config bean (optional)
     * @return A configured SDKConfiguration instance
     */
    @Bean
    @ConditionalOnMissingBean
    public SDKConfiguration sdkConfiguration(
            OpenapiAutoConfigProperties properties,
            HTTPClient httpClient,
            studio.livepeer.livepeer.utils.Hooks hooks,
            studio.livepeer.livepeer.utils.AsyncHooks asyncHooks,
            SecuritySource securitySource,
            Optional<RetryConfig> retryConfig) {
        
        SDKConfiguration sdkConfiguration = new SDKConfiguration();
        
        sdkConfiguration.setClient(httpClient);
        
        sdkConfiguration.setHooks(hooks);
        sdkConfiguration.setAsyncHooks(asyncHooks);
        sdkConfiguration.setSecuritySource(securitySource);
        
        if (properties.getServerUrl() != null) {
            sdkConfiguration.setServerUrl(properties.getServerUrl());
        }
        sdkConfiguration.setServerIdx(properties.getServerIdx());
        
        sdkConfiguration.setRetryConfig(retryConfig);
        
        return sdkConfiguration;
    }

    /**
     * Creates the main SDK bean using the configured SDKConfiguration.
     *
     * @param sdkConfiguration the configured SDKConfiguration bean
     * @return A configured Livepeer instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Livepeer livepeer(SDKConfiguration sdkConfiguration) {
        return new Livepeer(sdkConfiguration);
    }

    /**
     * Creates an AsyncHooks bean if none exists.
     * 
     * @return A configured AsyncHooks instance
     */
    @Bean
    @ConditionalOnMissingBean
    public studio.livepeer.livepeer.utils.AsyncHooks asyncHooks() {
        return new studio.livepeer.livepeer.utils.AsyncHooks();
    }

    /**
     * Creates a ScheduledExecutorService for async retry operations if none exists.
     * 
     * @return A configured ScheduledExecutorService instance
     */
    @Bean
    @ConditionalOnMissingBean
    public ScheduledExecutorService retryScheduler() {
        return Executors.newSingleThreadScheduledExecutor();
    }

    /**
     * Creates a Hooks configuration bean if none exists.
     *
     * @return A configured Hooks instance
     */
    @Bean
    @ConditionalOnMissingBean
    public studio.livepeer.livepeer.utils.Hooks hooks() {
        return new studio.livepeer.livepeer.utils.Hooks();
    }
    /**
     * Creates a Stream sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Stream instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Stream stream(Livepeer livepeer) {
        return livepeer.stream();
    }
    /**
     * Creates a Multistream sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Multistream instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Multistream multistream(Livepeer livepeer) {
        return livepeer.multistream();
    }
    /**
     * Creates a Webhook sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Webhook instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Webhook webhook(Livepeer livepeer) {
        return livepeer.webhook();
    }
    /**
     * Creates a Asset sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Asset instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Asset asset(Livepeer livepeer) {
        return livepeer.asset();
    }
    /**
     * Creates a Session sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Session instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Session session(Livepeer livepeer) {
        return livepeer.session();
    }
    /**
     * Creates a Room sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Room instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Room room(Livepeer livepeer) {
        return livepeer.room();
    }
    /**
     * Creates a Metrics sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Metrics instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Metrics metrics(Livepeer livepeer) {
        return livepeer.metrics();
    }
    /**
     * Creates a AccessControl sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured AccessControl instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AccessControl accessControl(Livepeer livepeer) {
        return livepeer.accessControl();
    }
    /**
     * Creates a Task sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Task instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Task task(Livepeer livepeer) {
        return livepeer.task();
    }
    /**
     * Creates a Transcode sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Transcode instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Transcode transcode(Livepeer livepeer) {
        return livepeer.transcode();
    }
    /**
     * Creates a Playback sub-SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @return A configured Playback instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Playback playback(Livepeer livepeer) {
        return livepeer.playback();
    }

    /**
     * Creates the async SDK bean if none exists.
     *
     * @param livepeer the main SDK instance
     * @param sdkConfiguration the configured SDKConfiguration bean
     * @return A configured AsyncLivepeer instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncLivepeer asyncLivepeer(Livepeer livepeer, SDKConfiguration sdkConfiguration) {
        return new AsyncLivepeer(livepeer, sdkConfiguration);
    }
    /**
     * Creates an AsyncStream sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncStream instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncStream asyncStream(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.stream();
    }
    /**
     * Creates an AsyncMultistream sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncMultistream instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncMultistream asyncMultistream(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.multistream();
    }
    /**
     * Creates an AsyncWebhook sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncWebhook instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncWebhook asyncWebhook(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.webhook();
    }
    /**
     * Creates an AsyncAsset sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncAsset instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncAsset asyncAsset(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.asset();
    }
    /**
     * Creates an AsyncSession sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncSession instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncSession asyncSession(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.session();
    }
    /**
     * Creates an AsyncRoom sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncRoom instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncRoom asyncRoom(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.room();
    }
    /**
     * Creates an AsyncMetrics sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncMetrics instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncMetrics asyncMetrics(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.metrics();
    }
    /**
     * Creates an AsyncAccessControl sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncAccessControl instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncAccessControl asyncAccessControl(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.accessControl();
    }
    /**
     * Creates an AsyncTask sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncTask instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncTask asyncTask(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.task();
    }
    /**
     * Creates an AsyncTranscode sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncTranscode instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncTranscode asyncTranscode(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.transcode();
    }
    /**
     * Creates an AsyncPlayback sub-SDK bean if none exists.
     *
     * @param asyncLivepeer the async SDK instance
     * @return A configured AsyncPlayback instance
     */
    @Bean
    @ConditionalOnMissingBean
    public AsyncPlayback asyncPlayback(AsyncLivepeer asyncLivepeer) {
        return asyncLivepeer.playback();
    }
}