/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer;

import static studio.livepeer.livepeer.operations.Operations.AsyncRequestlessOperation;
import static studio.livepeer.livepeer.operations.Operations.AsyncRequestOperation;

import java.lang.String;
import java.util.concurrent.CompletableFuture;
import studio.livepeer.livepeer.models.operations.DeleteSigningKeyRequest;
import studio.livepeer.livepeer.models.operations.GetSigningKeyRequest;
import studio.livepeer.livepeer.models.operations.UpdateSigningKeyRequest;
import studio.livepeer.livepeer.models.operations.UpdateSigningKeyRequestBody;
import studio.livepeer.livepeer.models.operations.async.CreateSigningKeyRequestBuilder;
import studio.livepeer.livepeer.models.operations.async.CreateSigningKeyResponse;
import studio.livepeer.livepeer.models.operations.async.DeleteSigningKeyRequestBuilder;
import studio.livepeer.livepeer.models.operations.async.DeleteSigningKeyResponse;
import studio.livepeer.livepeer.models.operations.async.GetSigningKeyRequestBuilder;
import studio.livepeer.livepeer.models.operations.async.GetSigningKeyResponse;
import studio.livepeer.livepeer.models.operations.async.GetSigningKeysRequestBuilder;
import studio.livepeer.livepeer.models.operations.async.GetSigningKeysResponse;
import studio.livepeer.livepeer.models.operations.async.UpdateSigningKeyRequestBuilder;
import studio.livepeer.livepeer.models.operations.async.UpdateSigningKeyResponse;
import studio.livepeer.livepeer.operations.CreateSigningKey;
import studio.livepeer.livepeer.operations.DeleteSigningKey;
import studio.livepeer.livepeer.operations.GetSigningKey;
import studio.livepeer.livepeer.operations.GetSigningKeys;
import studio.livepeer.livepeer.operations.UpdateSigningKey;
import studio.livepeer.livepeer.utils.Headers;

/**
 * Operations related to access control/signing keys api
 */
public class AsyncAccessControl {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AccessControl syncSDK;

    AsyncAccessControl(AccessControl syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public AccessControl sync() {
        return syncSDK;
    }


    /**
     * Create a signing key
     * 
     * <p>The publicKey is a representation of the public key, encoded as base 64 and is passed as a string,
     * and  the privateKey is displayed only on creation. This is the only moment where the client can save
     * the private key, otherwise it will be lost. Remember to decode your string when signing JWTs.
     * Up to 10 signing keys can be generated, after that you must delete at least one signing key to
     * create a new one.
     * 
     * @return The async call builder
     */
    public CreateSigningKeyRequestBuilder create() {
        return new CreateSigningKeyRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a signing key
     * 
     * <p>The publicKey is a representation of the public key, encoded as base 64 and is passed as a string,
     * and  the privateKey is displayed only on creation. This is the only moment where the client can save
     * the private key, otherwise it will be lost. Remember to decode your string when signing JWTs.
     * Up to 10 signing keys can be generated, after that you must delete at least one signing key to
     * create a new one.
     * 
     * @return {@code CompletableFuture<CreateSigningKeyResponse>} - The async response
     */
    public CompletableFuture<CreateSigningKeyResponse> createDirect() {
        AsyncRequestlessOperation<CreateSigningKeyResponse> operation
            = new CreateSigningKey.Async(sdkConfiguration, _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }


    /**
     * Retrieves signing keys
     * 
     * @return The async call builder
     */
    public GetSigningKeysRequestBuilder getAll() {
        return new GetSigningKeysRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieves signing keys
     * 
     * @return {@code CompletableFuture<GetSigningKeysResponse>} - The async response
     */
    public CompletableFuture<GetSigningKeysResponse> getAllDirect() {
        AsyncRequestlessOperation<GetSigningKeysResponse> operation
            = new GetSigningKeys.Async(sdkConfiguration, _headers);
        return operation.doRequest()
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete Signing Key
     * 
     * @return The async call builder
     */
    public DeleteSigningKeyRequestBuilder delete() {
        return new DeleteSigningKeyRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete Signing Key
     * 
     * @param keyId ID of the signing key
     * @return {@code CompletableFuture<DeleteSigningKeyResponse>} - The async response
     */
    public CompletableFuture<DeleteSigningKeyResponse> delete(String keyId) {
        DeleteSigningKeyRequest request =
            DeleteSigningKeyRequest
                .builder()
                .keyId(keyId)
                .build();
        AsyncRequestOperation<DeleteSigningKeyRequest, DeleteSigningKeyResponse> operation
              = new DeleteSigningKey.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Retrieves a signing key
     * 
     * @return The async call builder
     */
    public GetSigningKeyRequestBuilder get() {
        return new GetSigningKeyRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieves a signing key
     * 
     * @param keyId ID of the signing key
     * @return {@code CompletableFuture<GetSigningKeyResponse>} - The async response
     */
    public CompletableFuture<GetSigningKeyResponse> get(String keyId) {
        GetSigningKeyRequest request =
            GetSigningKeyRequest
                .builder()
                .keyId(keyId)
                .build();
        AsyncRequestOperation<GetSigningKeyRequest, GetSigningKeyResponse> operation
              = new GetSigningKey.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Update a signing key
     * 
     * @return The async call builder
     */
    public UpdateSigningKeyRequestBuilder update() {
        return new UpdateSigningKeyRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a signing key
     * 
     * @param keyId ID of the signing key
     * @param requestBody 
     * @return {@code CompletableFuture<UpdateSigningKeyResponse>} - The async response
     */
    public CompletableFuture<UpdateSigningKeyResponse> update(String keyId, UpdateSigningKeyRequestBody requestBody) {
        UpdateSigningKeyRequest request =
            UpdateSigningKeyRequest
                .builder()
                .keyId(keyId)
                .requestBody(requestBody)
                .build();
        AsyncRequestOperation<UpdateSigningKeyRequest, UpdateSigningKeyResponse> operation
              = new UpdateSigningKey.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
