/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer;

import static studio.livepeer.livepeer.operations.Operations.AsyncRequestOperation;

import java.util.concurrent.CompletableFuture;
import studio.livepeer.livepeer.models.components.TranscodePayload;
import studio.livepeer.livepeer.models.operations.async.TranscodeVideoRequestBuilder;
import studio.livepeer.livepeer.models.operations.async.TranscodeVideoResponse;
import studio.livepeer.livepeer.operations.TranscodeVideo;
import studio.livepeer.livepeer.utils.Headers;

/**
 * Operations related to transcode api
 */
public class AsyncTranscode {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Transcode syncSDK;

    AsyncTranscode(Transcode syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Transcode sync() {
        return syncSDK;
    }


    /**
     * Transcode a video
     * 
     * <p>`POST /transcode` transcodes a video file and uploads the results to the
     * specified storage service.
     * \
     * \
     * Transcoding is asynchronous so you will need to check the status of the
     * task in order to determine when transcoding is complete. The `id` field
     * in the response is the unique ID for the transcoding `Task`. The task
     * status can be queried using the [GET tasks
     * endpoint](https://docs.livepeer.org/reference/api/get-tasks):
     * \
     * \
     * When `status.phase` is `completed`,  transcoding will be complete and
     * the results will be stored in the storage service and the specified
     * output location.
     * \
     * \
     * The results will be available under `params.outputs.hls.path` and
     * `params.outputs.mp4.path` in the specified storage service.
     * ## Input
     * \
     * This endpoint currently supports the following inputs:
     * - HTTP
     * - S3 API Compatible Service
     * \
     * \
     * **HTTP**
     * \
     * A public HTTP URL can be used to read a video file.
     * ```json
     * {
     * "url": "https://www.example.com/video.mp4"
     * }
     * ```
     * | Name | Type   | Description                          |
     * | ---- | ------ | ------------------------------------ |
     * | url  | string | A public HTTP URL for the video file. |
     * 
     * <p>Note: For IPFS HTTP gateway URLs, the API currently only supports “path
     * style” URLs and does not support “subdomain style” URLs. The API will
     * support both styles of URLs in a future update.
     * \
     * \
     * **S3 API Compatible Service**
     * \
     * \
     * S3 credentials can be used to authenticate with a S3 API compatible
     * service to read a video file.
     * 
     * <p>```json
     * {
     * "type": "s3",
     * "endpoint": "https://gateway.storjshare.io",
     * "credentials": {
     * "accessKeyId": "$ACCESS_KEY_ID",
     * "secretAccessKey": "$SECRET_ACCESS_KEY"
     * },
     * "bucket": "inbucket",
     * "path": "/video/source.mp4"
     * }
     * ```
     * 
     * <p>## Storage
     * \
     * This endpoint currently supports the following storage services:
     * - S3 API Compatible Service
     * - Web3 Storage
     * \
     * \
     * **S3 API Compatible Service**
     * ```json
     * {
     * "type": "s3",
     * "endpoint": "https://gateway.storjshare.io",
     * "credentials": {
     * "accessKeyId": "$ACCESS_KEY_ID",
     * "secretAccessKey": "$SECRET_ACCESS_KEY"
     * },
     * "bucket": "mybucket"
     * }
     * ```
     * 
     * <p>**Web3 Storage**
     * 
     * <p>```json
     * {
     * "type": "web3.storage",
     * "credentials": {
     * "proof": "$UCAN_DELEGATION_PROOF",
     * }
     * }
     * ```
     * 
     * <p>## Outputs
     * \
     * This endpoint currently supports the following output types:
     * - HLS
     * - MP4
     * 
     * <p>**HLS**
     * 
     * <p>```json
     * {
     * "hls": {
     * "path": "/samplevideo/hls"
     * }
     * }
     * ```
     * 
     * <p>**MP4**
     * 
     * <p>```json
     * {
     * "mp4": {
     * "path": "/samplevideo/mp4"
     * }
     * }
     * ```
     * 
     * @return The async call builder
     */
    public TranscodeVideoRequestBuilder create() {
        return new TranscodeVideoRequestBuilder(sdkConfiguration);
    }

    /**
     * Transcode a video
     * 
     * <p>`POST /transcode` transcodes a video file and uploads the results to the
     * specified storage service.
     * \
     * \
     * Transcoding is asynchronous so you will need to check the status of the
     * task in order to determine when transcoding is complete. The `id` field
     * in the response is the unique ID for the transcoding `Task`. The task
     * status can be queried using the [GET tasks
     * endpoint](https://docs.livepeer.org/reference/api/get-tasks):
     * \
     * \
     * When `status.phase` is `completed`,  transcoding will be complete and
     * the results will be stored in the storage service and the specified
     * output location.
     * \
     * \
     * The results will be available under `params.outputs.hls.path` and
     * `params.outputs.mp4.path` in the specified storage service.
     * ## Input
     * \
     * This endpoint currently supports the following inputs:
     * - HTTP
     * - S3 API Compatible Service
     * \
     * \
     * **HTTP**
     * \
     * A public HTTP URL can be used to read a video file.
     * ```json
     * {
     * "url": "https://www.example.com/video.mp4"
     * }
     * ```
     * | Name | Type   | Description                          |
     * | ---- | ------ | ------------------------------------ |
     * | url  | string | A public HTTP URL for the video file. |
     * 
     * <p>Note: For IPFS HTTP gateway URLs, the API currently only supports “path
     * style” URLs and does not support “subdomain style” URLs. The API will
     * support both styles of URLs in a future update.
     * \
     * \
     * **S3 API Compatible Service**
     * \
     * \
     * S3 credentials can be used to authenticate with a S3 API compatible
     * service to read a video file.
     * 
     * <p>```json
     * {
     * "type": "s3",
     * "endpoint": "https://gateway.storjshare.io",
     * "credentials": {
     * "accessKeyId": "$ACCESS_KEY_ID",
     * "secretAccessKey": "$SECRET_ACCESS_KEY"
     * },
     * "bucket": "inbucket",
     * "path": "/video/source.mp4"
     * }
     * ```
     * 
     * <p>## Storage
     * \
     * This endpoint currently supports the following storage services:
     * - S3 API Compatible Service
     * - Web3 Storage
     * \
     * \
     * **S3 API Compatible Service**
     * ```json
     * {
     * "type": "s3",
     * "endpoint": "https://gateway.storjshare.io",
     * "credentials": {
     * "accessKeyId": "$ACCESS_KEY_ID",
     * "secretAccessKey": "$SECRET_ACCESS_KEY"
     * },
     * "bucket": "mybucket"
     * }
     * ```
     * 
     * <p>**Web3 Storage**
     * 
     * <p>```json
     * {
     * "type": "web3.storage",
     * "credentials": {
     * "proof": "$UCAN_DELEGATION_PROOF",
     * }
     * }
     * ```
     * 
     * <p>## Outputs
     * \
     * This endpoint currently supports the following output types:
     * - HLS
     * - MP4
     * 
     * <p>**HLS**
     * 
     * <p>```json
     * {
     * "hls": {
     * "path": "/samplevideo/hls"
     * }
     * }
     * ```
     * 
     * <p>**MP4**
     * 
     * <p>```json
     * {
     * "mp4": {
     * "path": "/samplevideo/mp4"
     * }
     * }
     * ```
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<TranscodeVideoResponse>} - The async response
     */
    public CompletableFuture<TranscodeVideoResponse> create(TranscodePayload request) {
        AsyncRequestOperation<TranscodePayload, TranscodeVideoResponse> operation
              = new TranscodeVideo.Async(sdkConfiguration, _headers);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
