/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer;

import studio.livepeer.livepeer.utils.Headers;

/**
 * Livepeer API Reference: Welcome to the Livepeer API reference docs. Here you will find all the
 * endpoints exposed on the standard Livepeer API, learn how to use them and
 * what they return.
 */
public class AsyncLivepeer {
    private static final Headers _headers = Headers.EMPTY;
    /**
     * Operations related to livestream api
     */
    private final AsyncStream stream;
    /**
     * Operations related to multistream api
     */
    private final AsyncMultistream multistream;
    /**
     * Operations related to webhook api
     */
    private final AsyncWebhook webhook;
    /**
     * Operations related to asset/vod api
     */
    private final AsyncAsset asset;
    /**
     * Operations related to session api
     */
    private final AsyncSession session;
    /**
     * Operations related to rooms api
     */
    private final AsyncRoom room;
    /**
     * Operations related to metrics api
     */
    private final AsyncMetrics metrics;
    /**
     * Operations related to access control/signing keys api
     */
    private final AsyncAccessControl accessControl;
    /**
     * Operations related to tasks api
     */
    private final AsyncTask task;
    /**
     * Operations related to transcode api
     */
    private final AsyncTranscode transcode;
    /**
     * Operations related to playback api
     */
    private final AsyncPlayback playback;
    /**
     * Operations related to livestream api
     */
    public AsyncStream stream() {
        return stream;
    }
    /**
     * Operations related to multistream api
     */
    public AsyncMultistream multistream() {
        return multistream;
    }
    /**
     * Operations related to webhook api
     */
    public AsyncWebhook webhook() {
        return webhook;
    }
    /**
     * Operations related to asset/vod api
     */
    public AsyncAsset asset() {
        return asset;
    }
    /**
     * Operations related to session api
     */
    public AsyncSession session() {
        return session;
    }
    /**
     * Operations related to rooms api
     */
    public AsyncRoom room() {
        return room;
    }
    /**
     * Operations related to metrics api
     */
    public AsyncMetrics metrics() {
        return metrics;
    }
    /**
     * Operations related to access control/signing keys api
     */
    public AsyncAccessControl accessControl() {
        return accessControl;
    }
    /**
     * Operations related to tasks api
     */
    public AsyncTask task() {
        return task;
    }
    /**
     * Operations related to transcode api
     */
    public AsyncTranscode transcode() {
        return transcode;
    }
    /**
     * Operations related to playback api
     */
    public AsyncPlayback playback() {
        return playback;
    }

    private final SDKConfiguration sdkConfiguration;
    private final Livepeer syncSDK;

    AsyncLivepeer(Livepeer syncSDK, SDKConfiguration sdkConfiguration) {
        this.syncSDK = syncSDK;
        this.sdkConfiguration = sdkConfiguration;
        this.stream = new AsyncStream(syncSDK.stream(), sdkConfiguration);
        this.multistream = new AsyncMultistream(syncSDK.multistream(), sdkConfiguration);
        this.webhook = new AsyncWebhook(syncSDK.webhook(), sdkConfiguration);
        this.asset = new AsyncAsset(syncSDK.asset(), sdkConfiguration);
        this.session = new AsyncSession(syncSDK.session(), sdkConfiguration);
        this.room = new AsyncRoom(syncSDK.room(), sdkConfiguration);
        this.metrics = new AsyncMetrics(syncSDK.metrics(), sdkConfiguration);
        this.accessControl = new AsyncAccessControl(syncSDK.accessControl(), sdkConfiguration);
        this.task = new AsyncTask(syncSDK.task(), sdkConfiguration);
        this.transcode = new AsyncTranscode(syncSDK.transcode(), sdkConfiguration);
        this.playback = new AsyncPlayback(syncSDK.playback(), sdkConfiguration);
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public Livepeer sync() {
        return syncSDK;
    }
}
