/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer;

import static studio.livepeer.livepeer.operations.Operations.RequestlessOperation;
import static studio.livepeer.livepeer.operations.Operations.RequestOperation;

import java.lang.Deprecated;
import java.lang.Exception;
import java.lang.String;
import studio.livepeer.livepeer.models.components.RoomEgressPayload;
import studio.livepeer.livepeer.models.components.RoomUserPayload;
import studio.livepeer.livepeer.models.components.RoomUserUpdatePayload;
import studio.livepeer.livepeer.models.operations.CreateRoomRequestBuilder;
import studio.livepeer.livepeer.models.operations.CreateRoomResponse;
import studio.livepeer.livepeer.models.operations.CreateRoomUserRequest;
import studio.livepeer.livepeer.models.operations.CreateRoomUserRequestBuilder;
import studio.livepeer.livepeer.models.operations.CreateRoomUserResponse;
import studio.livepeer.livepeer.models.operations.DeleteRoomRequest;
import studio.livepeer.livepeer.models.operations.DeleteRoomRequestBuilder;
import studio.livepeer.livepeer.models.operations.DeleteRoomResponse;
import studio.livepeer.livepeer.models.operations.DeleteRoomUserRequest;
import studio.livepeer.livepeer.models.operations.DeleteRoomUserRequestBuilder;
import studio.livepeer.livepeer.models.operations.DeleteRoomUserResponse;
import studio.livepeer.livepeer.models.operations.GetRoomRequest;
import studio.livepeer.livepeer.models.operations.GetRoomRequestBuilder;
import studio.livepeer.livepeer.models.operations.GetRoomResponse;
import studio.livepeer.livepeer.models.operations.GetRoomUserRequest;
import studio.livepeer.livepeer.models.operations.GetRoomUserRequestBuilder;
import studio.livepeer.livepeer.models.operations.GetRoomUserResponse;
import studio.livepeer.livepeer.models.operations.StartRoomEgressRequest;
import studio.livepeer.livepeer.models.operations.StartRoomEgressRequestBuilder;
import studio.livepeer.livepeer.models.operations.StartRoomEgressResponse;
import studio.livepeer.livepeer.models.operations.StopRoomEgressRequest;
import studio.livepeer.livepeer.models.operations.StopRoomEgressRequestBuilder;
import studio.livepeer.livepeer.models.operations.StopRoomEgressResponse;
import studio.livepeer.livepeer.models.operations.UpdateRoomUserRequest;
import studio.livepeer.livepeer.models.operations.UpdateRoomUserRequestBuilder;
import studio.livepeer.livepeer.models.operations.UpdateRoomUserResponse;
import studio.livepeer.livepeer.operations.CreateRoom;
import studio.livepeer.livepeer.operations.CreateRoomUser;
import studio.livepeer.livepeer.operations.DeleteRoom;
import studio.livepeer.livepeer.operations.DeleteRoomUser;
import studio.livepeer.livepeer.operations.GetRoom;
import studio.livepeer.livepeer.operations.GetRoomUser;
import studio.livepeer.livepeer.operations.StartRoomEgress;
import studio.livepeer.livepeer.operations.StopRoomEgress;
import studio.livepeer.livepeer.operations.UpdateRoomUser;
import studio.livepeer.livepeer.utils.Headers;

/**
 * Operations related to rooms api
 */
public class Room {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncRoom asyncSDK;

    Room(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncRoom(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncRoom async() {
        return asyncSDK;
    }

    /**
     * Create a room
     * 
     * <p>Create a multiparticipant livestreaming room.
     * 
     * @return The call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CreateRoomRequestBuilder create() {
        return new CreateRoomRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a room
     * 
     * <p>Create a multiparticipant livestreaming room.
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CreateRoomResponse createDirect() throws Exception {
        RequestlessOperation<CreateRoomResponse> operation
            = new CreateRoom.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest());
    }

    /**
     * Retrieve a room
     * 
     * @return The call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public GetRoomRequestBuilder get() {
        return new GetRoomRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a room
     * 
     * @param id 
     * @return The response from the API call
     * @throws Exception if the API call fails
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public GetRoomResponse get(String id) throws Exception {
        GetRoomRequest request =
            GetRoomRequest
                .builder()
                .id(id)
                .build();
        RequestOperation<GetRoomRequest, GetRoomResponse> operation
              = new GetRoom.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete a room
     * 
     * @return The call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public DeleteRoomRequestBuilder delete() {
        return new DeleteRoomRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a room
     * 
     * @param id 
     * @return The response from the API call
     * @throws Exception if the API call fails
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public DeleteRoomResponse delete(String id) throws Exception {
        DeleteRoomRequest request =
            DeleteRoomRequest
                .builder()
                .id(id)
                .build();
        RequestOperation<DeleteRoomRequest, DeleteRoomResponse> operation
              = new DeleteRoom.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Start room RTMP egress
     * 
     * <p>Create a livestream for your room.
     * This allows you to leverage livestreaming features like recording and HLS output.
     * 
     * @return The call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public StartRoomEgressRequestBuilder startEgress() {
        return new StartRoomEgressRequestBuilder(sdkConfiguration);
    }

    /**
     * Start room RTMP egress
     * 
     * <p>Create a livestream for your room.
     * This allows you to leverage livestreaming features like recording and HLS output.
     * 
     * @param id 
     * @param roomEgressPayload 
     * @return The response from the API call
     * @throws Exception if the API call fails
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public StartRoomEgressResponse startEgress(String id, RoomEgressPayload roomEgressPayload) throws Exception {
        StartRoomEgressRequest request =
            StartRoomEgressRequest
                .builder()
                .id(id)
                .roomEgressPayload(roomEgressPayload)
                .build();
        RequestOperation<StartRoomEgressRequest, StartRoomEgressResponse> operation
              = new StartRoomEgress.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Stop room RTMP egress
     * 
     * @return The call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public StopRoomEgressRequestBuilder stopEgress() {
        return new StopRoomEgressRequestBuilder(sdkConfiguration);
    }

    /**
     * Stop room RTMP egress
     * 
     * @param id 
     * @return The response from the API call
     * @throws Exception if the API call fails
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public StopRoomEgressResponse stopEgress(String id) throws Exception {
        StopRoomEgressRequest request =
            StopRoomEgressRequest
                .builder()
                .id(id)
                .build();
        RequestOperation<StopRoomEgressRequest, StopRoomEgressResponse> operation
              = new StopRoomEgress.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a room user
     * 
     * <p>Call this endpoint to add a user to a room, specifying a display name at a minimum.
     * The response will contain a joining URL for Livepeer's default meeting app.
     * Alternatively the joining token can be used with a custom app.
     * 
     * @return The call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CreateRoomUserRequestBuilder createUser() {
        return new CreateRoomUserRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a room user
     * 
     * <p>Call this endpoint to add a user to a room, specifying a display name at a minimum.
     * The response will contain a joining URL for Livepeer's default meeting app.
     * Alternatively the joining token can be used with a custom app.
     * 
     * @param id 
     * @param roomUserPayload 
     * @return The response from the API call
     * @throws Exception if the API call fails
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public CreateRoomUserResponse createUser(String id, RoomUserPayload roomUserPayload) throws Exception {
        CreateRoomUserRequest request =
            CreateRoomUserRequest
                .builder()
                .id(id)
                .roomUserPayload(roomUserPayload)
                .build();
        RequestOperation<CreateRoomUserRequest, CreateRoomUserResponse> operation
              = new CreateRoomUser.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get user details
     * 
     * @return The call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public GetRoomUserRequestBuilder getUser() {
        return new GetRoomUserRequestBuilder(sdkConfiguration);
    }

    /**
     * Get user details
     * 
     * @param id 
     * @param userId 
     * @return The response from the API call
     * @throws Exception if the API call fails
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public GetRoomUserResponse getUser(String id, String userId) throws Exception {
        GetRoomUserRequest request =
            GetRoomUserRequest
                .builder()
                .id(id)
                .userId(userId)
                .build();
        RequestOperation<GetRoomUserRequest, GetRoomUserResponse> operation
              = new GetRoomUser.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a room user
     * 
     * <p>Update properties for a user.
     * 
     * @return The call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public UpdateRoomUserRequestBuilder updateUser() {
        return new UpdateRoomUserRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a room user
     * 
     * <p>Update properties for a user.
     * 
     * @param id 
     * @param userId 
     * @param roomUserUpdatePayload 
     * @return The response from the API call
     * @throws Exception if the API call fails
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public UpdateRoomUserResponse updateUser(
            String id, String userId,
            RoomUserUpdatePayload roomUserUpdatePayload) throws Exception {
        UpdateRoomUserRequest request =
            UpdateRoomUserRequest
                .builder()
                .id(id)
                .userId(userId)
                .roomUserUpdatePayload(roomUserUpdatePayload)
                .build();
        RequestOperation<UpdateRoomUserRequest, UpdateRoomUserResponse> operation
              = new UpdateRoomUser.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Remove a user from the room
     * 
     * @return The call builder
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public DeleteRoomUserRequestBuilder deleteUser() {
        return new DeleteRoomUserRequestBuilder(sdkConfiguration);
    }

    /**
     * Remove a user from the room
     * 
     * @param id 
     * @param userId 
     * @return The response from the API call
     * @throws Exception if the API call fails
     * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    @Deprecated
    public DeleteRoomUserResponse deleteUser(String id, String userId) throws Exception {
        DeleteRoomUserRequest request =
            DeleteRoomUserRequest
                .builder()
                .id(id)
                .userId(userId)
                .build();
        RequestOperation<DeleteRoomUserRequest, DeleteRoomUserResponse> operation
              = new DeleteRoomUser.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
