/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer;

import static studio.livepeer.livepeer.operations.Operations.RequestOperation;

import java.lang.Exception;
import java.lang.String;
import java.util.Optional;
import studio.livepeer.livepeer.models.components.ClipPayload;
import studio.livepeer.livepeer.models.components.NewStreamPayload;
import studio.livepeer.livepeer.models.components.StreamPatchPayload;
import studio.livepeer.livepeer.models.components.TargetAddPayload;
import studio.livepeer.livepeer.models.operations.AddMultistreamTargetRequest;
import studio.livepeer.livepeer.models.operations.AddMultistreamTargetRequestBuilder;
import studio.livepeer.livepeer.models.operations.AddMultistreamTargetResponse;
import studio.livepeer.livepeer.models.operations.CreateClipRequestBuilder;
import studio.livepeer.livepeer.models.operations.CreateClipResponse;
import studio.livepeer.livepeer.models.operations.CreateStreamRequestBuilder;
import studio.livepeer.livepeer.models.operations.CreateStreamResponse;
import studio.livepeer.livepeer.models.operations.DeleteStreamRequest;
import studio.livepeer.livepeer.models.operations.DeleteStreamRequestBuilder;
import studio.livepeer.livepeer.models.operations.DeleteStreamResponse;
import studio.livepeer.livepeer.models.operations.GetClipsRequest;
import studio.livepeer.livepeer.models.operations.GetClipsRequestBuilder;
import studio.livepeer.livepeer.models.operations.GetClipsResponse;
import studio.livepeer.livepeer.models.operations.GetStreamRequest;
import studio.livepeer.livepeer.models.operations.GetStreamRequestBuilder;
import studio.livepeer.livepeer.models.operations.GetStreamResponse;
import studio.livepeer.livepeer.models.operations.GetStreamsRequest;
import studio.livepeer.livepeer.models.operations.GetStreamsRequestBuilder;
import studio.livepeer.livepeer.models.operations.GetStreamsResponse;
import studio.livepeer.livepeer.models.operations.RemoveMultistreamTargetRequest;
import studio.livepeer.livepeer.models.operations.RemoveMultistreamTargetRequestBuilder;
import studio.livepeer.livepeer.models.operations.RemoveMultistreamTargetResponse;
import studio.livepeer.livepeer.models.operations.StartPullStreamRequest;
import studio.livepeer.livepeer.models.operations.StartPullStreamRequestBuilder;
import studio.livepeer.livepeer.models.operations.StartPullStreamResponse;
import studio.livepeer.livepeer.models.operations.TerminateStreamRequest;
import studio.livepeer.livepeer.models.operations.TerminateStreamRequestBuilder;
import studio.livepeer.livepeer.models.operations.TerminateStreamResponse;
import studio.livepeer.livepeer.models.operations.UpdateStreamRequest;
import studio.livepeer.livepeer.models.operations.UpdateStreamRequestBuilder;
import studio.livepeer.livepeer.models.operations.UpdateStreamResponse;
import studio.livepeer.livepeer.operations.AddMultistreamTarget;
import studio.livepeer.livepeer.operations.CreateClip;
import studio.livepeer.livepeer.operations.CreateStream;
import studio.livepeer.livepeer.operations.DeleteStream;
import studio.livepeer.livepeer.operations.GetClips;
import studio.livepeer.livepeer.operations.GetStream;
import studio.livepeer.livepeer.operations.GetStreams;
import studio.livepeer.livepeer.operations.RemoveMultistreamTarget;
import studio.livepeer.livepeer.operations.StartPullStream;
import studio.livepeer.livepeer.operations.TerminateStream;
import studio.livepeer.livepeer.operations.UpdateStream;
import studio.livepeer.livepeer.utils.Headers;

/**
 * Operations related to livestream api
 */
public class Stream {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncStream asyncSDK;

    Stream(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncStream(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncStream async() {
        return asyncSDK;
    }

    /**
     * Create a stream
     * 
     * <p>The only parameter you are required to set is the name of your stream,
     * but we also highly recommend that you define transcoding profiles
     * parameter that suits your specific broadcasting configuration.
     * \
     * \
     * If you do not define transcoding rendition profiles when creating the
     * stream, a default set of profiles will be used. These profiles include
     * 240p,  360p, 480p and 720p.
     * \
     * \
     * The playback policy is set to public by default for new streams. It can
     * also be added upon the creation of a new stream by adding
     * `"playbackPolicy": {"type": "jwt"}`
     * 
     * @return The call builder
     */
    public CreateStreamRequestBuilder create() {
        return new CreateStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a stream
     * 
     * <p>The only parameter you are required to set is the name of your stream,
     * but we also highly recommend that you define transcoding profiles
     * parameter that suits your specific broadcasting configuration.
     * \
     * \
     * If you do not define transcoding rendition profiles when creating the
     * stream, a default set of profiles will be used. These profiles include
     * 240p,  360p, 480p and 720p.
     * \
     * \
     * The playback policy is set to public by default for new streams. It can
     * also be added upon the creation of a new stream by adding
     * `"playbackPolicy": {"type": "jwt"}`
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public CreateStreamResponse create(NewStreamPayload request) throws Exception {
        RequestOperation<NewStreamPayload, CreateStreamResponse> operation
              = new CreateStream.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve streams
     * 
     * @return The call builder
     */
    public GetStreamsRequestBuilder getAll() {
        return new GetStreamsRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve streams
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetStreamsResponse getAllDirect() throws Exception {
        return getAll(Optional.empty());
    }

    /**
     * Retrieve streams
     * 
     * @param streamsonly 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetStreamsResponse getAll(Optional<String> streamsonly) throws Exception {
        GetStreamsRequest request =
            GetStreamsRequest
                .builder()
                .streamsonly(streamsonly)
                .build();
        RequestOperation<GetStreamsRequest, GetStreamsResponse> operation
              = new GetStreams.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a stream
     * 
     * @return The call builder
     */
    public GetStreamRequestBuilder get() {
        return new GetStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a stream
     * 
     * @param id ID of the stream
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetStreamResponse get(String id) throws Exception {
        GetStreamRequest request =
            GetStreamRequest
                .builder()
                .id(id)
                .build();
        RequestOperation<GetStreamRequest, GetStreamResponse> operation
              = new GetStream.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a stream
     * 
     * @return The call builder
     */
    public UpdateStreamRequestBuilder update() {
        return new UpdateStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a stream
     * 
     * @param id ID of the stream
     * @param streamPatchPayload 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public UpdateStreamResponse update(String id, StreamPatchPayload streamPatchPayload) throws Exception {
        UpdateStreamRequest request =
            UpdateStreamRequest
                .builder()
                .id(id)
                .streamPatchPayload(streamPatchPayload)
                .build();
        RequestOperation<UpdateStreamRequest, UpdateStreamResponse> operation
              = new UpdateStream.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete a stream
     * 
     * <p>This will also suspend any active stream sessions, so make sure to wait
     * until the stream has finished. To explicitly interrupt an active
     * session, consider instead updating the suspended field in the stream
     * using the PATCH stream API.
     * 
     * @return The call builder
     */
    public DeleteStreamRequestBuilder delete() {
        return new DeleteStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete a stream
     * 
     * <p>This will also suspend any active stream sessions, so make sure to wait
     * until the stream has finished. To explicitly interrupt an active
     * session, consider instead updating the suspended field in the stream
     * using the PATCH stream API.
     * 
     * @param id ID of the stream
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public DeleteStreamResponse delete(String id) throws Exception {
        DeleteStreamRequest request =
            DeleteStreamRequest
                .builder()
                .id(id)
                .build();
        RequestOperation<DeleteStreamRequest, DeleteStreamResponse> operation
              = new DeleteStream.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Terminates a live stream
     * 
     * <p>`DELETE /stream/{id}/terminate` can be used to terminate an ongoing
     * session on a live stream. Unlike suspending the stream, it allows the
     * streamer to restart streaming even immediately, but it will force
     * terminate the current session and stop the recording.
     * \
     * \
     * A 204 No Content status response indicates the stream was successfully
     * terminated.
     * 
     * @return The call builder
     */
    public TerminateStreamRequestBuilder terminate() {
        return new TerminateStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Terminates a live stream
     * 
     * <p>`DELETE /stream/{id}/terminate` can be used to terminate an ongoing
     * session on a live stream. Unlike suspending the stream, it allows the
     * streamer to restart streaming even immediately, but it will force
     * terminate the current session and stop the recording.
     * \
     * \
     * A 204 No Content status response indicates the stream was successfully
     * terminated.
     * 
     * @param id ID of the stream
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public TerminateStreamResponse terminate(String id) throws Exception {
        TerminateStreamRequest request =
            TerminateStreamRequest
                .builder()
                .id(id)
                .build();
        RequestOperation<TerminateStreamRequest, TerminateStreamResponse> operation
              = new TerminateStream.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Start ingest for a pull stream
     * 
     * <p>`POST /stream/{id}/start-pull` can be used to start ingest for a stream
     * configured with a pull source. If the stream has recording configured,
     * it will also start recording.
     * \
     * \
     * A 204 No Content status response indicates the stream was successfully
     * started.
     * 
     * @return The call builder
     */
    public StartPullStreamRequestBuilder startPull() {
        return new StartPullStreamRequestBuilder(sdkConfiguration);
    }

    /**
     * Start ingest for a pull stream
     * 
     * <p>`POST /stream/{id}/start-pull` can be used to start ingest for a stream
     * configured with a pull source. If the stream has recording configured,
     * it will also start recording.
     * \
     * \
     * A 204 No Content status response indicates the stream was successfully
     * started.
     * 
     * @param id ID of the stream
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public StartPullStreamResponse startPull(String id) throws Exception {
        StartPullStreamRequest request =
            StartPullStreamRequest
                .builder()
                .id(id)
                .build();
        RequestOperation<StartPullStreamRequest, StartPullStreamResponse> operation
              = new StartPullStream.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a clip
     * 
     * @return The call builder
     */
    public CreateClipRequestBuilder createClip() {
        return new CreateClipRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a clip
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public CreateClipResponse createClip(ClipPayload request) throws Exception {
        RequestOperation<ClipPayload, CreateClipResponse> operation
              = new CreateClip.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve clips of a livestream
     * 
     * @return The call builder
     */
    public GetClipsRequestBuilder getClips() {
        return new GetClipsRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve clips of a livestream
     * 
     * @param id ID of the parent stream or playbackId of parent stream
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetClipsResponse getClips(String id) throws Exception {
        GetClipsRequest request =
            GetClipsRequest
                .builder()
                .id(id)
                .build();
        RequestOperation<GetClipsRequest, GetClipsResponse> operation
              = new GetClips.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Add a multistream target
     * 
     * @return The call builder
     */
    public AddMultistreamTargetRequestBuilder addMultistreamTarget() {
        return new AddMultistreamTargetRequestBuilder(sdkConfiguration);
    }

    /**
     * Add a multistream target
     * 
     * @param id ID of the parent stream
     * @param targetAddPayload 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public AddMultistreamTargetResponse addMultistreamTarget(String id, TargetAddPayload targetAddPayload) throws Exception {
        AddMultistreamTargetRequest request =
            AddMultistreamTargetRequest
                .builder()
                .id(id)
                .targetAddPayload(targetAddPayload)
                .build();
        RequestOperation<AddMultistreamTargetRequest, AddMultistreamTargetResponse> operation
              = new AddMultistreamTarget.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Remove a multistream target
     * 
     * @return The call builder
     */
    public RemoveMultistreamTargetRequestBuilder removeMultistreamTarget() {
        return new RemoveMultistreamTargetRequestBuilder(sdkConfiguration);
    }

    /**
     * Remove a multistream target
     * 
     * @param id ID of the parent stream
     * @param targetId ID of the multistream target
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public RemoveMultistreamTargetResponse removeMultistreamTarget(String id, String targetId) throws Exception {
        RemoveMultistreamTargetRequest request =
            RemoveMultistreamTargetRequest
                .builder()
                .id(id)
                .targetId(targetId)
                .build();
        RequestOperation<RemoveMultistreamTargetRequest, RemoveMultistreamTargetResponse> operation
              = new RemoveMultistreamTarget.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
