/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import studio.livepeer.livepeer.utils.Utils;


public class AssetIpfsInput {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("spec")
    private Optional<? extends AssetSpec> spec;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("$ref")
    private Optional<? extends java.lang.Object> dollarRef;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nftMetadata")
    private Optional<? extends IpfsFileInfoInput> nftMetadata;

    @JsonCreator
    public AssetIpfsInput(
            @JsonProperty("spec") Optional<? extends AssetSpec> spec,
            @JsonProperty("$ref") Optional<? extends java.lang.Object> dollarRef,
            @JsonProperty("nftMetadata") Optional<? extends IpfsFileInfoInput> nftMetadata) {
        Utils.checkNotNull(spec, "spec");
        Utils.checkNotNull(dollarRef, "dollarRef");
        Utils.checkNotNull(nftMetadata, "nftMetadata");
        this.spec = spec;
        this.dollarRef = dollarRef;
        this.nftMetadata = nftMetadata;
    }
    
    public AssetIpfsInput() {
        this(Optional.empty(), Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<AssetSpec> spec() {
        return (Optional<AssetSpec>) spec;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<java.lang.Object> dollarRef() {
        return (Optional<java.lang.Object>) dollarRef;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<IpfsFileInfoInput> nftMetadata() {
        return (Optional<IpfsFileInfoInput>) nftMetadata;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public AssetIpfsInput withSpec(AssetSpec spec) {
        Utils.checkNotNull(spec, "spec");
        this.spec = Optional.ofNullable(spec);
        return this;
    }

    public AssetIpfsInput withSpec(Optional<? extends AssetSpec> spec) {
        Utils.checkNotNull(spec, "spec");
        this.spec = spec;
        return this;
    }

    public AssetIpfsInput withDollarRef(java.lang.Object dollarRef) {
        Utils.checkNotNull(dollarRef, "dollarRef");
        this.dollarRef = Optional.ofNullable(dollarRef);
        return this;
    }

    public AssetIpfsInput withDollarRef(Optional<? extends java.lang.Object> dollarRef) {
        Utils.checkNotNull(dollarRef, "dollarRef");
        this.dollarRef = dollarRef;
        return this;
    }

    public AssetIpfsInput withNftMetadata(IpfsFileInfoInput nftMetadata) {
        Utils.checkNotNull(nftMetadata, "nftMetadata");
        this.nftMetadata = Optional.ofNullable(nftMetadata);
        return this;
    }

    public AssetIpfsInput withNftMetadata(Optional<? extends IpfsFileInfoInput> nftMetadata) {
        Utils.checkNotNull(nftMetadata, "nftMetadata");
        this.nftMetadata = nftMetadata;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AssetIpfsInput other = (AssetIpfsInput) o;
        return 
            java.util.Objects.deepEquals(this.spec, other.spec) &&
            java.util.Objects.deepEquals(this.dollarRef, other.dollarRef) &&
            java.util.Objects.deepEquals(this.nftMetadata, other.nftMetadata);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            spec,
            dollarRef,
            nftMetadata);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AssetIpfsInput.class,
                "spec", spec,
                "dollarRef", dollarRef,
                "nftMetadata", nftMetadata);
    }
    
    public final static class Builder {
 
        private Optional<? extends AssetSpec> spec = Optional.empty();
 
        private Optional<? extends java.lang.Object> dollarRef = Optional.empty();
 
        private Optional<? extends IpfsFileInfoInput> nftMetadata = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder spec(AssetSpec spec) {
            Utils.checkNotNull(spec, "spec");
            this.spec = Optional.ofNullable(spec);
            return this;
        }

        public Builder spec(Optional<? extends AssetSpec> spec) {
            Utils.checkNotNull(spec, "spec");
            this.spec = spec;
            return this;
        }

        public Builder dollarRef(java.lang.Object dollarRef) {
            Utils.checkNotNull(dollarRef, "dollarRef");
            this.dollarRef = Optional.ofNullable(dollarRef);
            return this;
        }

        public Builder dollarRef(Optional<? extends java.lang.Object> dollarRef) {
            Utils.checkNotNull(dollarRef, "dollarRef");
            this.dollarRef = dollarRef;
            return this;
        }

        public Builder nftMetadata(IpfsFileInfoInput nftMetadata) {
            Utils.checkNotNull(nftMetadata, "nftMetadata");
            this.nftMetadata = Optional.ofNullable(nftMetadata);
            return this;
        }

        public Builder nftMetadata(Optional<? extends IpfsFileInfoInput> nftMetadata) {
            Utils.checkNotNull(nftMetadata, "nftMetadata");
            this.nftMetadata = nftMetadata;
            return this;
        }
        
        public AssetIpfsInput build() {
            return new AssetIpfsInput(
                spec,
                dollarRef,
                nftMetadata);
        }
    }
}

