/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import studio.livepeer.livepeer.utils.Utils;

/**
 * Export
 * 
 * <p>Output of the export task
 */
public class Export {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("ipfs")
    private Optional<? extends TaskIpfs> ipfs;

    @JsonCreator
    public Export(
            @JsonProperty("ipfs") Optional<? extends TaskIpfs> ipfs) {
        Utils.checkNotNull(ipfs, "ipfs");
        this.ipfs = ipfs;
    }
    
    public Export() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<TaskIpfs> ipfs() {
        return (Optional<TaskIpfs>) ipfs;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Export withIpfs(TaskIpfs ipfs) {
        Utils.checkNotNull(ipfs, "ipfs");
        this.ipfs = Optional.ofNullable(ipfs);
        return this;
    }


    public Export withIpfs(Optional<? extends TaskIpfs> ipfs) {
        Utils.checkNotNull(ipfs, "ipfs");
        this.ipfs = ipfs;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Export other = (Export) o;
        return 
            Utils.enhancedDeepEquals(this.ipfs, other.ipfs);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            ipfs);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Export.class,
                "ipfs", ipfs);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends TaskIpfs> ipfs = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder ipfs(TaskIpfs ipfs) {
            Utils.checkNotNull(ipfs, "ipfs");
            this.ipfs = Optional.ofNullable(ipfs);
            return this;
        }

        public Builder ipfs(Optional<? extends TaskIpfs> ipfs) {
            Utils.checkNotNull(ipfs, "ipfs");
            this.ipfs = ipfs;
            return this;
        }

        public Export build() {

            return new Export(
                ipfs);
        }

    }
}
