/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import studio.livepeer.livepeer.utils.Utils;


public class IpfsExportParams {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("$ref")
    private Optional<? extends java.lang.Object> dollarRef;

    /**
     * Custom credentials for the Piñata service. Must have either
     * a JWT or an API key and an API secret.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pinata")
    private Optional<? extends Pinata> pinata;

    @JsonCreator
    public IpfsExportParams(
            @JsonProperty("$ref") Optional<? extends java.lang.Object> dollarRef,
            @JsonProperty("pinata") Optional<? extends Pinata> pinata) {
        Utils.checkNotNull(dollarRef, "dollarRef");
        Utils.checkNotNull(pinata, "pinata");
        this.dollarRef = dollarRef;
        this.pinata = pinata;
    }
    
    public IpfsExportParams() {
        this(Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<java.lang.Object> dollarRef() {
        return (Optional<java.lang.Object>) dollarRef;
    }

    /**
     * Custom credentials for the Piñata service. Must have either
     * a JWT or an API key and an API secret.
     * 
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Pinata> pinata() {
        return (Optional<Pinata>) pinata;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public IpfsExportParams withDollarRef(java.lang.Object dollarRef) {
        Utils.checkNotNull(dollarRef, "dollarRef");
        this.dollarRef = Optional.ofNullable(dollarRef);
        return this;
    }

    public IpfsExportParams withDollarRef(Optional<? extends java.lang.Object> dollarRef) {
        Utils.checkNotNull(dollarRef, "dollarRef");
        this.dollarRef = dollarRef;
        return this;
    }

    /**
     * Custom credentials for the Piñata service. Must have either
     * a JWT or an API key and an API secret.
     * 
     */
    public IpfsExportParams withPinata(Pinata pinata) {
        Utils.checkNotNull(pinata, "pinata");
        this.pinata = Optional.ofNullable(pinata);
        return this;
    }

    /**
     * Custom credentials for the Piñata service. Must have either
     * a JWT or an API key and an API secret.
     * 
     */
    public IpfsExportParams withPinata(Optional<? extends Pinata> pinata) {
        Utils.checkNotNull(pinata, "pinata");
        this.pinata = pinata;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IpfsExportParams other = (IpfsExportParams) o;
        return 
            java.util.Objects.deepEquals(this.dollarRef, other.dollarRef) &&
            java.util.Objects.deepEquals(this.pinata, other.pinata);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            dollarRef,
            pinata);
    }
    
    @Override
    public String toString() {
        return Utils.toString(IpfsExportParams.class,
                "dollarRef", dollarRef,
                "pinata", pinata);
    }
    
    public final static class Builder {
 
        private Optional<? extends java.lang.Object> dollarRef = Optional.empty();
 
        private Optional<? extends Pinata> pinata = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder dollarRef(java.lang.Object dollarRef) {
            Utils.checkNotNull(dollarRef, "dollarRef");
            this.dollarRef = Optional.ofNullable(dollarRef);
            return this;
        }

        public Builder dollarRef(Optional<? extends java.lang.Object> dollarRef) {
            Utils.checkNotNull(dollarRef, "dollarRef");
            this.dollarRef = dollarRef;
            return this;
        }

        /**
         * Custom credentials for the Piñata service. Must have either
         * a JWT or an API key and an API secret.
         * 
         */
        public Builder pinata(Pinata pinata) {
            Utils.checkNotNull(pinata, "pinata");
            this.pinata = Optional.ofNullable(pinata);
            return this;
        }

        /**
         * Custom credentials for the Piñata service. Must have either
         * a JWT or an API key and an API secret.
         * 
         */
        public Builder pinata(Optional<? extends Pinata> pinata) {
            Utils.checkNotNull(pinata, "pinata");
            this.pinata = pinata;
            return this;
        }
        
        public IpfsExportParams build() {
            return new IpfsExportParams(
                dollarRef,
                pinata);
        }
    }
}

