/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum Name {
    VERIFIABLE_VIDEO("Verifiable Video");

    @JsonValue
    private final String value;

    Name(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Name> fromValue(String value) {
        for (Name o: Name.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

