/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

/**
 * One
 * 
 * <p>0: not mobile, 1: mobile screen share, 2: mobile camera.
 */
public enum One {
    ZERO(0L),
    ONE(1L),
    TWO(2L);

    @JsonValue
    private final long value;

    One(long value) {
        this.value = value;
    }
    
    public long value() {
        return value;
    }
    
    public static Optional<One> fromValue(long value) {
        for (One o: One.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

