/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import studio.livepeer.livepeer.utils.Utils;


public class Participants {

    /**
     * participant ID
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identity")
    private Optional<String> identity;

    /**
     * user defined participant name
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    private Optional<String> name;

    /**
     * the time the participant joined
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("joinedAt")
    private Optional<Long> joinedAt;

    /**
     * the time the participant left
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("leftAt")
    private Optional<Long> leftAt;

    @JsonCreator
    public Participants(
            @JsonProperty("identity") Optional<String> identity,
            @JsonProperty("name") Optional<String> name,
            @JsonProperty("joinedAt") Optional<Long> joinedAt,
            @JsonProperty("leftAt") Optional<Long> leftAt) {
        Utils.checkNotNull(identity, "identity");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(joinedAt, "joinedAt");
        Utils.checkNotNull(leftAt, "leftAt");
        this.identity = identity;
        this.name = name;
        this.joinedAt = joinedAt;
        this.leftAt = leftAt;
    }
    
    public Participants() {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * participant ID
     */
    @JsonIgnore
    public Optional<String> identity() {
        return identity;
    }

    /**
     * user defined participant name
     */
    @JsonIgnore
    public Optional<String> name() {
        return name;
    }

    /**
     * the time the participant joined
     */
    @JsonIgnore
    public Optional<Long> joinedAt() {
        return joinedAt;
    }

    /**
     * the time the participant left
     */
    @JsonIgnore
    public Optional<Long> leftAt() {
        return leftAt;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * participant ID
     */
    public Participants withIdentity(String identity) {
        Utils.checkNotNull(identity, "identity");
        this.identity = Optional.ofNullable(identity);
        return this;
    }

    /**
     * participant ID
     */
    public Participants withIdentity(Optional<String> identity) {
        Utils.checkNotNull(identity, "identity");
        this.identity = identity;
        return this;
    }

    /**
     * user defined participant name
     */
    public Participants withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }

    /**
     * user defined participant name
     */
    public Participants withName(Optional<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * the time the participant joined
     */
    public Participants withJoinedAt(long joinedAt) {
        Utils.checkNotNull(joinedAt, "joinedAt");
        this.joinedAt = Optional.ofNullable(joinedAt);
        return this;
    }

    /**
     * the time the participant joined
     */
    public Participants withJoinedAt(Optional<Long> joinedAt) {
        Utils.checkNotNull(joinedAt, "joinedAt");
        this.joinedAt = joinedAt;
        return this;
    }

    /**
     * the time the participant left
     */
    public Participants withLeftAt(long leftAt) {
        Utils.checkNotNull(leftAt, "leftAt");
        this.leftAt = Optional.ofNullable(leftAt);
        return this;
    }

    /**
     * the time the participant left
     */
    public Participants withLeftAt(Optional<Long> leftAt) {
        Utils.checkNotNull(leftAt, "leftAt");
        this.leftAt = leftAt;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Participants other = (Participants) o;
        return 
            Objects.deepEquals(this.identity, other.identity) &&
            Objects.deepEquals(this.name, other.name) &&
            Objects.deepEquals(this.joinedAt, other.joinedAt) &&
            Objects.deepEquals(this.leftAt, other.leftAt);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            identity,
            name,
            joinedAt,
            leftAt);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Participants.class,
                "identity", identity,
                "name", name,
                "joinedAt", joinedAt,
                "leftAt", leftAt);
    }
    
    public final static class Builder {
 
        private Optional<String> identity = Optional.empty();
 
        private Optional<String> name = Optional.empty();
 
        private Optional<Long> joinedAt = Optional.empty();
 
        private Optional<Long> leftAt = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * participant ID
         */
        public Builder identity(String identity) {
            Utils.checkNotNull(identity, "identity");
            this.identity = Optional.ofNullable(identity);
            return this;
        }

        /**
         * participant ID
         */
        public Builder identity(Optional<String> identity) {
            Utils.checkNotNull(identity, "identity");
            this.identity = identity;
            return this;
        }

        /**
         * user defined participant name
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * user defined participant name
         */
        public Builder name(Optional<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        /**
         * the time the participant joined
         */
        public Builder joinedAt(long joinedAt) {
            Utils.checkNotNull(joinedAt, "joinedAt");
            this.joinedAt = Optional.ofNullable(joinedAt);
            return this;
        }

        /**
         * the time the participant joined
         */
        public Builder joinedAt(Optional<Long> joinedAt) {
            Utils.checkNotNull(joinedAt, "joinedAt");
            this.joinedAt = joinedAt;
            return this;
        }

        /**
         * the time the participant left
         */
        public Builder leftAt(long leftAt) {
            Utils.checkNotNull(leftAt, "leftAt");
            this.leftAt = Optional.ofNullable(leftAt);
            return this;
        }

        /**
         * the time the participant left
         */
        public Builder leftAt(Optional<Long> leftAt) {
            Utils.checkNotNull(leftAt, "leftAt");
            this.leftAt = leftAt;
            return this;
        }
        
        public Participants build() {
            return new Participants(
                identity,
                name,
                joinedAt,
                leftAt);
        }
    }
}

