/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum PlaybackInfoMetaDvrPlaybackType {
    HTML5_APPLICATION_VND_APPLE_MPEGURL("html5/application/vnd.apple.mpegurl");

    @JsonValue
    private final String value;

    PlaybackInfoMetaDvrPlaybackType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PlaybackInfoMetaDvrPlaybackType> fromValue(String value) {
        for (PlaybackInfoMetaDvrPlaybackType o: PlaybackInfoMetaDvrPlaybackType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

