/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import studio.livepeer.livepeer.utils.Utils;

public class RoomUserPayload {

    /**
     * Display name
     */
    @JsonProperty("name")
    private String name;

    /**
     * Whether a user is allowed to publish audio/video tracks
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("canPublish")
    private Optional<? extends Boolean> canPublish;

    /**
     * Whether a user is allowed to publish data messages to the room
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("canPublishData")
    private Optional<? extends Boolean> canPublishData;

    /**
     * User defined payload to store for the participant
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    private Optional<? extends String> metadata;

    @JsonCreator
    public RoomUserPayload(
            @JsonProperty("name") String name,
            @JsonProperty("canPublish") Optional<? extends Boolean> canPublish,
            @JsonProperty("canPublishData") Optional<? extends Boolean> canPublishData,
            @JsonProperty("metadata") Optional<? extends String> metadata) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(canPublish, "canPublish");
        Utils.checkNotNull(canPublishData, "canPublishData");
        Utils.checkNotNull(metadata, "metadata");
        this.name = name;
        this.canPublish = canPublish;
        this.canPublishData = canPublishData;
        this.metadata = metadata;
    }
    
    public RoomUserPayload(
            String name) {
        this(name, Optional.empty(), Optional.empty(), Optional.empty());
    }

    /**
     * Display name
     */
    @JsonIgnore
    public String name() {
        return name;
    }

    /**
     * Whether a user is allowed to publish audio/video tracks
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Boolean> canPublish() {
        return (Optional<Boolean>) canPublish;
    }

    /**
     * Whether a user is allowed to publish data messages to the room
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Boolean> canPublishData() {
        return (Optional<Boolean>) canPublishData;
    }

    /**
     * User defined payload to store for the participant
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> metadata() {
        return (Optional<String>) metadata;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Display name
     */
    public RoomUserPayload withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * Whether a user is allowed to publish audio/video tracks
     */
    public RoomUserPayload withCanPublish(boolean canPublish) {
        Utils.checkNotNull(canPublish, "canPublish");
        this.canPublish = Optional.ofNullable(canPublish);
        return this;
    }

    /**
     * Whether a user is allowed to publish audio/video tracks
     */
    public RoomUserPayload withCanPublish(Optional<? extends Boolean> canPublish) {
        Utils.checkNotNull(canPublish, "canPublish");
        this.canPublish = canPublish;
        return this;
    }

    /**
     * Whether a user is allowed to publish data messages to the room
     */
    public RoomUserPayload withCanPublishData(boolean canPublishData) {
        Utils.checkNotNull(canPublishData, "canPublishData");
        this.canPublishData = Optional.ofNullable(canPublishData);
        return this;
    }

    /**
     * Whether a user is allowed to publish data messages to the room
     */
    public RoomUserPayload withCanPublishData(Optional<? extends Boolean> canPublishData) {
        Utils.checkNotNull(canPublishData, "canPublishData");
        this.canPublishData = canPublishData;
        return this;
    }

    /**
     * User defined payload to store for the participant
     */
    public RoomUserPayload withMetadata(String metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = Optional.ofNullable(metadata);
        return this;
    }

    /**
     * User defined payload to store for the participant
     */
    public RoomUserPayload withMetadata(Optional<? extends String> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = metadata;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RoomUserPayload other = (RoomUserPayload) o;
        return 
            java.util.Objects.deepEquals(this.name, other.name) &&
            java.util.Objects.deepEquals(this.canPublish, other.canPublish) &&
            java.util.Objects.deepEquals(this.canPublishData, other.canPublishData) &&
            java.util.Objects.deepEquals(this.metadata, other.metadata);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            name,
            canPublish,
            canPublishData,
            metadata);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RoomUserPayload.class,
                "name", name,
                "canPublish", canPublish,
                "canPublishData", canPublishData,
                "metadata", metadata);
    }
    
    public final static class Builder {
 
        private String name;
 
        private Optional<? extends Boolean> canPublish = Optional.empty();
 
        private Optional<? extends Boolean> canPublishData = Optional.empty();
 
        private Optional<? extends String> metadata = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Display name
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        /**
         * Whether a user is allowed to publish audio/video tracks
         */
        public Builder canPublish(boolean canPublish) {
            Utils.checkNotNull(canPublish, "canPublish");
            this.canPublish = Optional.ofNullable(canPublish);
            return this;
        }

        /**
         * Whether a user is allowed to publish audio/video tracks
         */
        public Builder canPublish(Optional<? extends Boolean> canPublish) {
            Utils.checkNotNull(canPublish, "canPublish");
            this.canPublish = canPublish;
            return this;
        }

        /**
         * Whether a user is allowed to publish data messages to the room
         */
        public Builder canPublishData(boolean canPublishData) {
            Utils.checkNotNull(canPublishData, "canPublishData");
            this.canPublishData = Optional.ofNullable(canPublishData);
            return this;
        }

        /**
         * Whether a user is allowed to publish data messages to the room
         */
        public Builder canPublishData(Optional<? extends Boolean> canPublishData) {
            Utils.checkNotNull(canPublishData, "canPublishData");
            this.canPublishData = canPublishData;
            return this;
        }

        /**
         * User defined payload to store for the participant
         */
        public Builder metadata(String metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * User defined payload to store for the participant
         */
        public Builder metadata(Optional<? extends String> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = metadata;
            return this;
        }
        
        public RoomUserPayload build() {
            return new RoomUserPayload(
                name,
                canPublish,
                canPublishData,
                metadata);
        }
    }
}

