/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum SignatureType {
    EIP712("eip712"),
    FLOW("flow");

    @JsonValue
    private final String value;

    private SignatureType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
