/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;


import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Objects;
import studio.livepeer.livepeer.utils.OneOfDeserializer;
import studio.livepeer.livepeer.utils.TypedObject;
import studio.livepeer.livepeer.utils.Utils.JsonShape;
import studio.livepeer.livepeer.utils.Utils.TypeReferenceWithShape;
import studio.livepeer.livepeer.utils.Utils;


@JsonDeserialize(using = Source._Deserializer.class)
public class Source {

    @JsonValue
    private TypedObject value;
    
    private Source(TypedObject value) {
        this.value = value;
    }

    public static Source of(Source1 value) {
        Utils.checkNotNull(value, "value");
        return new Source(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Source1>(){}));
    }

    public static Source of(Two value) {
        Utils.checkNotNull(value, "value");
        return new Source(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Two>(){}));
    }

    public static Source of(Source3 value) {
        Utils.checkNotNull(value, "value");
        return new Source(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Source3>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code studio.livepeer.livepeer.models.components.Source1}</li>
     * <li>{@code studio.livepeer.livepeer.models.components.Two}</li>
     * <li>{@code studio.livepeer.livepeer.models.components.Source3}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Source other = (Source) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<Source> {

        public _Deserializer() {
            super(Source.class, false,
                  TypeReferenceWithShape.of(new TypeReference<Source3>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Source1>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Two>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(Source.class,
                "value", value);
    }
 
}
