/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import studio.livepeer.livepeer.utils.Utils;


public class StorageStatus {

    /**
     * Phase of the asset storage
     */
    @JsonProperty("phase")
    private Phase phase;

    /**
     * Current progress of the task updating the storage.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("progress")
    private Optional<Double> progress;

    /**
     * Error message if the last storage changed failed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("errorMessage")
    private Optional<String> errorMessage;

    @JsonProperty("tasks")
    private Tasks tasks;

    @JsonCreator
    public StorageStatus(
            @JsonProperty("phase") Phase phase,
            @JsonProperty("progress") Optional<Double> progress,
            @JsonProperty("errorMessage") Optional<String> errorMessage,
            @JsonProperty("tasks") Tasks tasks) {
        Utils.checkNotNull(phase, "phase");
        Utils.checkNotNull(progress, "progress");
        Utils.checkNotNull(errorMessage, "errorMessage");
        Utils.checkNotNull(tasks, "tasks");
        this.phase = phase;
        this.progress = progress;
        this.errorMessage = errorMessage;
        this.tasks = tasks;
    }
    
    public StorageStatus(
            Phase phase,
            Tasks tasks) {
        this(phase, Optional.empty(), Optional.empty(), tasks);
    }

    /**
     * Phase of the asset storage
     */
    @JsonIgnore
    public Phase phase() {
        return phase;
    }

    /**
     * Current progress of the task updating the storage.
     */
    @JsonIgnore
    public Optional<Double> progress() {
        return progress;
    }

    /**
     * Error message if the last storage changed failed.
     */
    @JsonIgnore
    public Optional<String> errorMessage() {
        return errorMessage;
    }

    @JsonIgnore
    public Tasks tasks() {
        return tasks;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Phase of the asset storage
     */
    public StorageStatus withPhase(Phase phase) {
        Utils.checkNotNull(phase, "phase");
        this.phase = phase;
        return this;
    }

    /**
     * Current progress of the task updating the storage.
     */
    public StorageStatus withProgress(double progress) {
        Utils.checkNotNull(progress, "progress");
        this.progress = Optional.ofNullable(progress);
        return this;
    }

    /**
     * Current progress of the task updating the storage.
     */
    public StorageStatus withProgress(Optional<Double> progress) {
        Utils.checkNotNull(progress, "progress");
        this.progress = progress;
        return this;
    }

    /**
     * Error message if the last storage changed failed.
     */
    public StorageStatus withErrorMessage(String errorMessage) {
        Utils.checkNotNull(errorMessage, "errorMessage");
        this.errorMessage = Optional.ofNullable(errorMessage);
        return this;
    }

    /**
     * Error message if the last storage changed failed.
     */
    public StorageStatus withErrorMessage(Optional<String> errorMessage) {
        Utils.checkNotNull(errorMessage, "errorMessage");
        this.errorMessage = errorMessage;
        return this;
    }

    public StorageStatus withTasks(Tasks tasks) {
        Utils.checkNotNull(tasks, "tasks");
        this.tasks = tasks;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StorageStatus other = (StorageStatus) o;
        return 
            Objects.deepEquals(this.phase, other.phase) &&
            Objects.deepEquals(this.progress, other.progress) &&
            Objects.deepEquals(this.errorMessage, other.errorMessage) &&
            Objects.deepEquals(this.tasks, other.tasks);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            phase,
            progress,
            errorMessage,
            tasks);
    }
    
    @Override
    public String toString() {
        return Utils.toString(StorageStatus.class,
                "phase", phase,
                "progress", progress,
                "errorMessage", errorMessage,
                "tasks", tasks);
    }
    
    public final static class Builder {
 
        private Phase phase;
 
        private Optional<Double> progress = Optional.empty();
 
        private Optional<String> errorMessage = Optional.empty();
 
        private Tasks tasks;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Phase of the asset storage
         */
        public Builder phase(Phase phase) {
            Utils.checkNotNull(phase, "phase");
            this.phase = phase;
            return this;
        }

        /**
         * Current progress of the task updating the storage.
         */
        public Builder progress(double progress) {
            Utils.checkNotNull(progress, "progress");
            this.progress = Optional.ofNullable(progress);
            return this;
        }

        /**
         * Current progress of the task updating the storage.
         */
        public Builder progress(Optional<Double> progress) {
            Utils.checkNotNull(progress, "progress");
            this.progress = progress;
            return this;
        }

        /**
         * Error message if the last storage changed failed.
         */
        public Builder errorMessage(String errorMessage) {
            Utils.checkNotNull(errorMessage, "errorMessage");
            this.errorMessage = Optional.ofNullable(errorMessage);
            return this;
        }

        /**
         * Error message if the last storage changed failed.
         */
        public Builder errorMessage(Optional<String> errorMessage) {
            Utils.checkNotNull(errorMessage, "errorMessage");
            this.errorMessage = errorMessage;
            return this;
        }

        public Builder tasks(Tasks tasks) {
            Utils.checkNotNull(tasks, "tasks");
            this.tasks = tasks;
            return this;
        }
        
        public StorageStatus build() {
            return new StorageStatus(
                phase,
                progress,
                errorMessage,
                tasks);
        }
    }
}

