/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import studio.livepeer.livepeer.utils.LazySingletonValue;
import studio.livepeer.livepeer.utils.Utils;


public class TargetOutput {

    /**
     * Name of transcoding profile that should be sent. Use
     * "source" for pushing source stream data
     * 
     */
    @JsonProperty("profile")
    private String profile;

    /**
     * If true, the stream audio will be muted and only silent
     * video will be pushed to the target.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("videoOnly")
    private Optional<? extends Boolean> videoOnly;

    /**
     * ID of multistream target object where to push this stream
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<? extends String> id;

    @JsonCreator
    public TargetOutput(
            @JsonProperty("profile") String profile,
            @JsonProperty("videoOnly") Optional<? extends Boolean> videoOnly,
            @JsonProperty("id") Optional<? extends String> id) {
        Utils.checkNotNull(profile, "profile");
        Utils.checkNotNull(videoOnly, "videoOnly");
        Utils.checkNotNull(id, "id");
        this.profile = profile;
        this.videoOnly = videoOnly;
        this.id = id;
    }
    
    public TargetOutput(
            String profile) {
        this(profile, Optional.empty(), Optional.empty());
    }

    /**
     * Name of transcoding profile that should be sent. Use
     * "source" for pushing source stream data
     * 
     */
    @JsonIgnore
    public String profile() {
        return profile;
    }

    /**
     * If true, the stream audio will be muted and only silent
     * video will be pushed to the target.
     * 
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Boolean> videoOnly() {
        return (Optional<Boolean>) videoOnly;
    }

    /**
     * ID of multistream target object where to push this stream
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> id() {
        return (Optional<String>) id;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Name of transcoding profile that should be sent. Use
     * "source" for pushing source stream data
     * 
     */
    public TargetOutput withProfile(String profile) {
        Utils.checkNotNull(profile, "profile");
        this.profile = profile;
        return this;
    }

    /**
     * If true, the stream audio will be muted and only silent
     * video will be pushed to the target.
     * 
     */
    public TargetOutput withVideoOnly(boolean videoOnly) {
        Utils.checkNotNull(videoOnly, "videoOnly");
        this.videoOnly = Optional.ofNullable(videoOnly);
        return this;
    }

    /**
     * If true, the stream audio will be muted and only silent
     * video will be pushed to the target.
     * 
     */
    public TargetOutput withVideoOnly(Optional<? extends Boolean> videoOnly) {
        Utils.checkNotNull(videoOnly, "videoOnly");
        this.videoOnly = videoOnly;
        return this;
    }

    /**
     * ID of multistream target object where to push this stream
     */
    public TargetOutput withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }

    /**
     * ID of multistream target object where to push this stream
     */
    public TargetOutput withId(Optional<? extends String> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TargetOutput other = (TargetOutput) o;
        return 
            java.util.Objects.deepEquals(this.profile, other.profile) &&
            java.util.Objects.deepEquals(this.videoOnly, other.videoOnly) &&
            java.util.Objects.deepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            profile,
            videoOnly,
            id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TargetOutput.class,
                "profile", profile,
                "videoOnly", videoOnly,
                "id", id);
    }
    
    public final static class Builder {
 
        private String profile;
 
        private Optional<? extends Boolean> videoOnly;
 
        private Optional<? extends String> id = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Name of transcoding profile that should be sent. Use
         * "source" for pushing source stream data
         * 
         */
        public Builder profile(String profile) {
            Utils.checkNotNull(profile, "profile");
            this.profile = profile;
            return this;
        }

        /**
         * If true, the stream audio will be muted and only silent
         * video will be pushed to the target.
         * 
         */
        public Builder videoOnly(boolean videoOnly) {
            Utils.checkNotNull(videoOnly, "videoOnly");
            this.videoOnly = Optional.ofNullable(videoOnly);
            return this;
        }

        /**
         * If true, the stream audio will be muted and only silent
         * video will be pushed to the target.
         * 
         */
        public Builder videoOnly(Optional<? extends Boolean> videoOnly) {
            Utils.checkNotNull(videoOnly, "videoOnly");
            this.videoOnly = videoOnly;
            return this;
        }

        /**
         * ID of multistream target object where to push this stream
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * ID of multistream target object where to push this stream
         */
        public Builder id(Optional<? extends String> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }
        
        public TargetOutput build() {
            if (videoOnly == null) {
                videoOnly = _SINGLETON_VALUE_VideoOnly.value();
            }
            return new TargetOutput(
                profile,
                videoOnly,
                id);
        }

        private static final LazySingletonValue<Optional<? extends Boolean>> _SINGLETON_VALUE_VideoOnly =
                new LazySingletonValue<>(
                        "videoOnly",
                        "false",
                        new TypeReference<Optional<? extends Boolean>>() {});
    }
}

