/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;


import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * TaskType - Type of the task
 */
public enum TaskType {
    UPLOAD("upload"),
    EXPORT("export"),
    EXPORT_DATA("export-data"),
    TRANSCODE_FILE("transcode-file"),
    CLIP("clip");

    @JsonValue
    private final String value;

    private TaskType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
