/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package studio.livepeer.livepeer.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum TranscodeProfileEncoder {
    H264("H.264"),
    HEVC("HEVC"),
    VP8("VP8"),
    VP9("VP9");

    @JsonValue
    private final String value;

    private TranscodeProfileEncoder(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
